import "dotenv/config";
import mongoose from "mongoose";
import Game from "../models/Game.js";
import connectDB from "../config/database.js";

const mode = process.argv[2] || "posters";

// ─── Poster & screenshot fixes ───
const posterFixes = {
  "Grand Theft Auto VI": {
    poster: "https://upload.wikimedia.org/wikipedia/en/4/46/Grand_Theft_Auto_VI.png",
    screenshots: [
      "https://rockstarintel.com/wp-content/uploads/2025/05/Vice_City_01.jpg",
      "https://rockstarintel.com/wp-content/uploads/2025/05/Lucia_Caminos_03.jpg",
      "https://rockstarintel.com/wp-content/uploads/2025/05/Jason_Duval_01.jpg",
      "https://rockstarintel.com/wp-content/uploads/2025/05/Grassrivers_01.jpg",
      "https://rockstarintel.com/wp-content/uploads/2025/05/Mount_Kalaga_National_Park_01.jpg",
      "https://rockstarintel.com/wp-content/uploads/2025/05/Ambrosia_01.jpg",
    ],
  },
  "Doom: The Dark Ages": {
    poster: "https://upload.wikimedia.org/wikipedia/en/7/7f/DOOM%2C_The_Dark_Ages_Game_Cover.jpeg",
    screenshots: [
      "https://upload.wikimedia.org/wikipedia/en/7/7f/DOOM%2C_The_Dark_Ages_Game_Cover.jpeg",
      "https://upload.wikimedia.org/wikipedia/en/f/fd/Doom_The_Dark_Ages_gameplay.jpg",
    ],
  },
  "Borderlands 4": {
    poster: "https://upload.wikimedia.org/wikipedia/en/f/fd/Borderlands_4_cover_art.jpg",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/f/fd/Borderlands_4_cover_art.jpg"],
  },
  "Elden Ring Nightreign": {
    poster: "https://upload.wikimedia.org/wikipedia/en/f/f0/Elden_Ring_Nightreign_cover_art.png",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/f/f0/Elden_Ring_Nightreign_cover_art.png"],
  },
  "Mafia: The Old Country": {
    poster: "https://upload.wikimedia.org/wikipedia/en/a/af/Mafia_The_Old_Country_cover_art.jpg",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/a/af/Mafia_The_Old_Country_cover_art.jpg"],
  },
  "Like a Dragon: Pirate Yakuza in Hawaii": {
    poster: "https://upload.wikimedia.org/wikipedia/en/8/81/Like_a_Dragon_Pirate_Yakuza_in_Hawaii_Cover_Art.jpg",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/8/81/Like_a_Dragon_Pirate_Yakuza_in_Hawaii_Cover_Art.jpg"],
  },
  "Clair Obscur: Expedition 33": {
    poster: "https://upload.wikimedia.org/wikipedia/en/5/5a/Clair_Obscur%2C_Expedition_33_Cover_1.webp",
    screenshots: [
      "https://upload.wikimedia.org/wikipedia/en/5/5a/Clair_Obscur%2C_Expedition_33_Cover_1.webp",
      "https://upload.wikimedia.org/wikipedia/en/6/6a/Clair_Obscur_gameplay_screenshot.png",
    ],
  },
  "South of Midnight": {
    poster: "https://upload.wikimedia.org/wikipedia/en/8/83/South_of_Midnight_cover_art.jpeg",
    screenshots: [
      "https://upload.wikimedia.org/wikipedia/en/8/83/South_of_Midnight_cover_art.jpeg",
      "https://upload.wikimedia.org/wikipedia/en/e/ed/South_of_Midnight_gameplay_screenshot.jpg",
    ],
  },
  "Death Stranding 2: On the Beach": {
    poster: "https://upload.wikimedia.org/wikipedia/en/e/e0/Death_Stranding_2_Icon.jpg",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/e/e0/Death_Stranding_2_Icon.jpg"],
  },
  Avowed: {
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avowed_key_art.jpeg",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/4/4d/Avowed_key_art.jpeg"],
  },
  "Metroid Prime 4: Beyond": {
    poster: "https://upload.wikimedia.org/wikipedia/en/4/48/Metroid_Prime_4_Beyond_cover_art.png",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/4/48/Metroid_Prime_4_Beyond_cover_art.png"],
  },
  Atomfall: {
    poster: "https://upload.wikimedia.org/wikipedia/en/1/13/Atomfall_cover_art.jpeg",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/1/13/Atomfall_cover_art.jpeg"],
  },
  "Gears of War: E-Day": {
    poster: "https://upload.wikimedia.org/wikipedia/en/9/9e/Gears_of_War_E-Day_cover_art.png",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/9/9e/Gears_of_War_E-Day_cover_art.png"],
  },
  "Ghost of Yotei": {
    poster: "https://upload.wikimedia.org/wikipedia/en/1/18/Ghost_of_Y%C5%8Dtei_cover_art.png",
    screenshots: [
      "https://upload.wikimedia.org/wikipedia/en/1/18/Ghost_of_Y%C5%8Dtei_cover_art.png",
      "https://sm.ign.com/t/ign_za/photo/default/4fff4e3964b95d390d4ed47a03083ea07096a58e-scaled-174541133221_feeu.1400.jpg",
      "https://sm.ign.com/t/ign_za/photo/default/56d9212f57f25d54034076e8ead8994e2dc8ed0c-scaled-174541133221_vwpn.1400.jpg",
      "https://sm.ign.com/t/ign_za/photo/default/4979261102fd41bcb641905bbd67179a8aeae516-scaled-174541133221_qz3g.1400.jpg",
      "https://sm.ign.com/t/ign_za/photo/default/6f36a9dd878b241b249dfba5214d6f7311ef32f3-scaled-174541133221_3m1s.1400.jpg",
      "https://sm.ign.com/t/ign_za/photo/default/efd95179e702db2937de88ac469065295c1a903c-1745411332216_5m6m.1400.jpg",
      "https://sm.ign.com/t/ign_za/photo/default/12f747e70ddd3d05eda2e203333e22153d970e89-scaled-174541133221_dfkd.1400.jpg",
    ],
  },
  "Marvel's Wolverine": {
    poster: "https://upload.wikimedia.org/wikipedia/en/3/3d/Marvel%27s_Wolverine_cover_art.jpg",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/3/3d/Marvel%27s_Wolverine_cover_art.jpg"],
  },
  "The First Berserker: Khazan": {
    poster: "https://upload.wikimedia.org/wikipedia/en/6/64/The_First_Berserker_Khazan_cover.jpg",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/6/64/The_First_Berserker_Khazan_cover.jpg"],
  },
  Fable: {
    poster: "https://upload.wikimedia.org/wikipedia/en/b/b8/Fable_key_art.png",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/b/b8/Fable_key_art.png"],
  },
  "The Witcher IV": {
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4c/The_Witcher_IV_logo.png",
    screenshots: ["https://upload.wikimedia.org/wikipedia/en/4/4c/The_Witcher_IV_logo.png"],
  },
};

// ─── Description updates ───
const descriptions = {
  "Grand Theft Auto VI": "The most anticipated game of the decade finally arrives. Return to Vice City and the surrounding state of Leonida in this massive open-world crime epic that pushes gaming technology to new heights. Play as Lucia and Jason in a modern-day Bonnie and Clyde narrative across a sprawling, hyper-detailed world. Every neighborhood has its own culture and rhythm. Dynamic world events, reactive AI, and an evolving ecosystem make Leonida feel alive. Improved combat mechanics include refined gunplay, deep hand-to-hand systems, and expanded vehicle combat. The online component launches with a\u5168\u65b0\u7684 shared-world experience featuring heists, businesses, and community events. Rockstar's signature storytelling, cutting-edge graphics, and infinite emergent gameplay redefine what video games can achieve. With ray-tracing, physics-driven destruction, and a soundtrack spanning decades of hits, GTA VI sets a new benchmark for interactive entertainment.",
  "Monster Hunter Wilds": "Hunt colossal monsters in a breathtaking open world where ecosystems evolve in real-time with dynamic weather, changing seasons, and living wildlife. Master 14 distinct weapon types, from the nimble dual blades to the devastating great sword, each with unique move sets and mechanics. Track monsters through dynamic environments where storms alter terrain, seasonal changes affect monster behavior, and resource availability shifts with the ecosystem. Seamless co-op hunting allows up to four players to team up across platforms with full cross-play support. The new mount system lets you ride and fight from your Seikret, adding vertical mobility and tactical options. The roster of monsters is the most ambitious in series history, including returning fan favorites and brand-new apex predators. Environments react to your actions, creating emergent gameplay moments that make every hunt unique. A living world that evolves with every expedition.",
  "Doom: The Dark Ages": "Rip and tear through a medieval fantasy world where demons have conquered the kingdom. As the legendary Slayer, wield brutal dark-age weaponry from enchanted swords and devastating maces to demon-infused crossbows and siege-grade ballistas. Explore sprawling gothic castles, hell-infested dungeons, corrupted forests, and besieged towns. Each environment tells a story of the demonic invasion through environmental storytelling and hidden lore. Combat is fluid and visceral, demanding constant movement, weapon switching, and strategic use of the environment. The new shield-saw lets you parry attacks, deflect projectiles, and rip enemies apart. Devastating finishers unleash screen-shaking glory kills that vary based on enemy type and environment. id Software's signature fluid combat engine delivers relentless action with a haunting heavy metal soundtrack that intensifies with the carnage. An epic prequel to the modern Doom saga.",
  "Death Stranding 2: On the Beach": "Continue Sam Bridges' extraordinary journey in a world struggling to reconnect after extinction-level events. Traverse hauntingly beautiful landscapes spanning vast tundras, sun-scorched deserts, and crumbling urban ruins. Face new supernatural threats called the 'Beach', a liminal space between life and death that bleeds into reality. Expanded traversal mechanics include improved vehicles, grappling hooks, zip-lines, and new equipment that fundamentally changes how you navigate. Combat has been completely redesigned with deeper stealth options, direct confrontation tools, and the ability to command NPC allies. The social strand system returns with more meaningful player connections and community-built infrastructure. Hideo Kojima's signature storytelling weaves emotional performances, philosophical themes, and thought-provoking narrative twists into an unforgettable experience. Featuring Norman Reedus, L\u00e9a Seydoux, and new cast members in a story that challenges perceptions of life, death, and human connection.",
  "Assassin's Creed Shadows": "Feudal Japan comes alive in breathtaking detail in this landmark Assassin's Creed adventure. Play as Naoe, a shinobi assassin who uses stealth, agility, and environmental tricks to eliminate targets, and Yasuke, the legendary African samurai who commands devastating melee combat and can face armies head-on. The dual-protagonist system lets you switch between characters, each with unique abilities, progression trees, and mission approaches. Explore a stunningly rendered 16th-century Japan spanning 30+ detailed cities, castles, and wilderness regions. Dynamic seasons transform the world: spring cherry blossoms obscure vision, summer rains silence footsteps, autumn leaves provide cover, and winter snow preserves footprints for tracking. Each season unlocks unique gameplay opportunities and challenges. The legendary Assassin vs. Templar conflict unfolds against a meticulously researched historical backdrop. Player choices reshape territories, alliances, and the fates of historical figures.",
  Avowed: "Explore the living world of Eora in this ambitious first-person RPG from Obsidian Entertainment, creators of Pillars of Eternity and The Outer Worlds. As an envoy of the Aedyr Empire, investigate a mysterious plague known as the Dreamscourge spreading through the Living Lands. Wield swords, axes, wands, and firearms in fluid real-time combat with seamless weapon switching and magical spellcasting. The deep ability system lets you mix and match skills from three skill trees: warrior, ranger, and wizard. Every choice matters \u2014 dialogue decisions, faction alliances, and quest outcomes reshape the world and determine the fate of its inhabitants. The reactive world changes based on your actions: towns remember your deeds, NPCs respond to your reputation, and major plot points branch based on your decisions. Obsidian's hallmark reactive storytelling delivers meaningful consequences and multiple endings. A richly detailed fantasy world with deep lore, compelling characters, and immersive exploration.",
  "Metroid Prime 4: Beyond": "Samus Aran returns in a brand-new first-person adventure that pushes the boundaries of the Metroid Prime formula to new heights. Explore alien worlds with unprecedented visual fidelity, from lush alien jungles to derelict space stations corrupted by Phazon. Engage in precision combat using Samus's full arsenal: arm cannon with multiple beam types, missiles, morph ball bombs, and new abilities. The iconic visor system returns with expanded scanning modes: combat visor for targeting, scan visor for lore and puzzles, thermal visor for hidden enemies, and new visor types that reveal dimensional anomalies. Environmental puzzles require creative use of upgrades and sequence-breaking opportunities for veteran players. Improved movement mechanics include wall jumps, speed booster, and new grapple techniques that make traversal fluid and rewarding. Intense boss battles test your mastery of combat and movement. A masterful blend of exploration, combat, and atmospheric storytelling that defines the Metroid franchise.",
  "Ghost of Yotei": "Set 300 years after the events of Ghost of Tsushima, a new Ghost rises in the shadow of Mount Yotei in feudal Japan's northern frontier. Play as Atsu, a warrior haunted by her past, armed with a new arsenal of weapons including dual katanas, chain sickles, and explosive powder bombs. The vast Ezo region features snow-capped mountains, dense forests, sprawling plains, and coastal villages, each with distinct weather and seasonal cycles that dynamically affect gameplay. Deep snow muffles footsteps but leaves tracks, rain extinguishes your bow, and fog limits visibility. New Ghost weapons expand tactical options: smoke bombs for escapes, wind chimes for distractions, and sticky bombs for traps. The stand-off system returns with new multi-enemy chain assassinations. A gripping story of vengeance, redemption, and identity unfolds against stunning landscapes rendered with Sucker Punch's signature visual artistry. Wind guides you to objectives, fireflies mark points of interest, and wildlife reacts to your presence.",
  "Borderlands 4": "The signature looter-shooter returns bigger, bolder, and more chaotic than ever with billions of procedurally generated weapons, each with unique handling, elemental effects, and special abilities. Explore a never-before-seen planet on the edge of known space, featuring diverse biomes from toxic wastelands and crystal forests to floating archipelagoes and alien hive cities. Choose from an all-new Vault Hunter roster, each with devastating action skills and deep skill trees that enable radically different playstyles. Drop-in/drop-out four-player co-op with dynamic difficulty scaling ensures the mayhem scales with your party. New elemental damage systems create devastating synergies, vehicle combat enhancements include customizable vehicles with mounted weapons, and the most chaotic skill trees yet offer unprecedented build variety. The signature cel-shaded art style returns with enhanced lighting and physics. Mayhem modifiers return with new game-altering mutations. Billions of guns. Infinite mayhem. Your next Vault Hunt begins now.",
  "Sid Meier's Civilization VII": "Lead your civilization from ancient antiquity to the distant space age in the next evolution of the legendary 4X strategy franchise. New gameplay systems fundamentally change how empires are built and managed. Dynamic diplomacy features AI leaders with genuine personalities who remember past grievances and alliances, negotiating with trade deals, territorial disputes, and military alliances. Enhanced warfare tactics include combined arms bonuses, siege mechanics, and commander units that provide army-wide buffs. Deeper cultural development paths let you shape your civilization's identity through government policies, religious beliefs, and philosophical traditions. The new age system divides history into distinct eras, each with unique challenges and victory conditions. Choose from the most diverse roster of leaders in franchise history, each with unique abilities, agendas, and customizable traits. Build your empire through science, culture, military might, economic dominance, or religious influence. The most ambitious Civilization game yet. One more turn...",
  "Split Fiction": "From Hazelight Studios, the award-winning creators of It Takes Two, comes a boundary-pushing co-op adventure where two writers, Zoe and Mio, become trapped inside their own stories. Navigate a genre-defying world that seamlessly shifts between sci-fi and fantasy, from cyberpunk cities and space stations to enchanted forests and dragon-guarded castles. Each level introduces unique mechanics that require constant communication and coordination between players. One player might manipulate gravity while the other controls time. Solve creative puzzles that demand both players contribute their unique abilities. Overcome dynamic obstacles that change in real-time based on your actions. Experience a heartfelt story about creativity, friendship, and the power of collaboration. Unique dual-character mechanics mean no two playthroughs are identical. Friend Pass lets one player invite another for free. This is cooperative gaming at its absolute finest.",
  Fable: "The legendary RPG series returns with a brand-new adventure filled with British humor, morally complex choices, and magical mayhem. Explore the land of Albion like never before \u2014 a sprawling fantasy world where every action has consequences. Your choices shape your character physically: good deeds make you radiant and attract helpful NPCs, while evil deeds cause physical corruption and inspire fear. Magic and melee combat have been completely reimagined with fluid real-time combat that lets you chain sword strikes, spells, and special abilities. Build relationships with villagers, get married, buy property, and build a family. The world ages around you: children become adults, buildings crumble or get renovated based on the economy, and your legend grows with every deed. Playground Games brings the beloved series into a stunning new era with cutting-edge visuals, a massive open world, and the signature humor that defined the franchise. Your story. Your choices. Your legend.",
  "The First Berserker: Khazan": "A hardcore action RPG set in the Dungeon Fighter Online universe that delivers punishing yet rewarding combat. As Khazan, the legendary berserker framed for treason, fight through brutal battlefields using precision-based combat mechanics that demand mastery of timing and positioning. Master three distinct weapon styles: dual swords for speed and combos, greatsword for power and reach, and spear for precision and crowd control. The parry system is central to combat \u2014 perfectly timed blocks leave enemies staggered and open for devastating counter-attacks. Unleash special skills through the skill tree, customizing Khazan's abilities to match your preferred playstyle. Challenging boss encounters are the highlight, each with unique attack patterns, phases, and weaknesses to discover. Stunning cel-shaded visuals bring the world to life with a distinctive art style that blends traditional Korean aesthetics with dark fantasy. A gripping revenge story set in a beautifully brutal world.",
  Atomfall: "Survive in a uniquely British post-apocalyptic open world set five years after the catastrophic Windscale nuclear disaster of 1957. The English countryside has been transformed into a radioactive wilderness, with towering nuclear vents, mutated wildlife, and desperate survivor settlements. Scavenge resources from abandoned villages, military outposts, and secret underground bunkers. Craft weapons, tools, and medicine from salvaged materials using an extensive crafting system. Investigate mysterious radio signals that lead to hidden facilities, secret government experiments, and a conspiracy that reaches the highest levels of power. Navigate irradiated zones with a Geiger counter, managing radiation exposure while searching for valuable loot. Face mutated creatures and desperate survivors who may be friend or foe. With its distinctive British setting, immersive survival mechanics, branching narrative, and multiple endings, Atomfall offers a uniquely British take on post-apocalyptic survival.",
  "Elden Ring Nightreign": "A standalone co-op survival experience set in the Elden Ring universe that combines signature FromSoftware challenge with roguelike mechanics. Face the Nightlord across three procedurally generated in-game days and nights, each cycle bringing new threats, rewards, and environmental conditions. By day, explore a shifting map to discover dungeons, defeat minibosses, and gather powerful equipment and upgrades. As night falls, the world becomes more dangerous with enhanced enemies and environmental hazards. Choose from unique classes with specialized abilities, combat styles, and ultimate skills. Master new mechanics including mounted combat, aerial attacks, and environmental interactions. The rune system lets you permanently unlock account-wide bonuses between runs. Faithful to the signature challenge while introducing fresh roguelike elements, this is a new way to experience the Lands Between. The night is dark and full of terrors. Survive.",
  "Mafia: The Old Country": "Experience the brutal origins of organized crime in 1900s Sicily in this gritty open-world crime drama from Hangar 13. Step into the boots of Enzo, a young man drawn into the world of the Sicilian Mafia during the tumultuous early 20th century. Build your criminal empire from the ground up through extortion, smuggling, and strategic alliances. Earn respect through brutal enforcement and navigate the complex codes of honor, loyalty, and silence that governed the original Cosa Nostra. Explore a beautifully realized historical Sicily: from the dusty streets of small villages to the opulent villas of wealthy landowners, from hidden mountain passes to bustling port cities. The authentic period detail extends to weapons, vehicles, and fashion of the era. Cinematic mission design with branching paths and moral choices that affect your standing with the family. A compelling prequel rooted in tradition, betrayal, and the making of an American legend.",
  "Like a Dragon: Pirate Yakuza in Hawaii": "Set sail for the most outrageous adventure in the Yakuza series yet as Goro Majima, now an amnesiac pirate captain washing ashore on a tropical island. Explore the seas around Hawaii in naval combat, commanding your own pirate ship with customizable weapons and crew. Switch between two combat styles: Mad Dog, a return to Majima's signature breakdance-inspired brutality, and Sea Dog, a new swashbuckling style featuring cutlass slashes and pistol shots. Build your pirate crew by recruiting colorful characters from across the series, each with unique abilities and side stories. Manage your ship, upgrade its weapons and speed, and engage in naval battles with rival pirate fleets. Explore sunken ruins, hidden coves, and treasure islands. The signature RGG Studio blend of serious drama and absurd humor is in full effect, with emotional main story beats and ridiculous side content including karaoke, arcade games, and the return of Cabaret Club. Yo-ho-ho, it's Yakuza like you've never seen it.",
  "Clair Obscur: Expedition 33": "A stunning turn-based RPG set in a painterly world where a mysterious Paintress annually erases a color from existence, killing everyone associated with it. Lead Expedition 33 on a desperate mission to confront the Paintress and end her devastating cycle. Explore a universe where beauty and danger intertwine, from the vibrant Belle \u00c9poque-inspired streets of Lumi\u00e8re to the monochrome wastelands of the Erased. The combat system blends traditional turn-based strategy with real-time action elements: time your attacks for critical hits, dodge incoming attacks with precise button presses, and chain abilities for devastating combos. The painterly art style evolves as colors are erased, with the world literally losing hues as the Paintress works. An emotional narrative explores themes of loss, memory, and sacrifice. Unique companion characters each have distinct combat roles and personal stories. One of the most visually striking RPGs ever made, with a soundtrack that adapts to your journey.",
  "South of Midnight": "Immerse yourself in the haunted American Deep South in this third-person action-adventure from Compulsion Games. Play as Hazel, a weaver with the supernatural ability to see and mend broken spirits, unravel curses, and restore balance to a world teetering between the living and the dead. Explore a beautifully grotesque world inspired by Southern Gothic folklore and mythology, from moss-draped bayous and crumbling antebellum mansions to hidden creature-filled caves and ghost-haunted swamps. Battle twisted creatures born from human misery using Hazel's weaving powers: mend enemies to weaken them, unravel their curses, and banish them with powerful spells. The unique art style blends stop-motion animation aesthetics with modern graphics technology, creating a distinctive visual identity. Uncover family secrets spanning generations, make moral choices that affect the spirit world, and discover the true cost of the supernatural. A deep, emotional journey through myth, memory, and the American South.",
  "The Witcher IV": "The next epic chapter in the Witcher saga begins, with Ciri taking her place as the protagonist. Hunt monsters across a vast continent transformed by war, political upheaval, and a mysterious cataclysm that has unleashed never-before-seen creatures. Master new magical abilities that build on Ciri's unique connection to Elder Blood, allowing unprecedented combat and exploration capabilities. Craft powerful witcher gear using new alchemy and crafting systems that offer deeper customization. Make morally complex choices that reshape the world \u2014 entire regions can change based on your decisions, factions rise and fall, and characters live or die by your actions. CD Projekt Red's next-generation REDengine delivers breathtaking visuals with ray-tracing, photorealistic characters, and a living world that reacts to your presence. Deeply reactive storytelling with multiple branching paths and endings ensures no two playthroughs are identical. A legend is reborn. The Witcher saga continues.",
  "Marvel's Wolverine": "Unleash your animal instincts in this visceral third-person action game from Insomniac Games, the studio behind Marvel's Spider-Man. Play as Logan \u2014 the best there is at what he does \u2014 in a mature, emotionally charged narrative that explores the character's brutal past and tortured present. Combat is raw and savage: tear through enemies with adamantium claws in fluid, cinematic combat that combines fast-paced melee attacks, stealth takedowns, and environmental kills. The rage system builds as you take damage, unlocking devastating berserker abilities that turn the tide of battle. Your regenerative healing factor is integrated into gameplay as a resource that recovers health but can be overwhelmed by sustained damage. Explore locations from seedy dive bars and Weapon X facilities to wilderness cabins and international espionage hubs. With the same care, polish, and quality that defined Marvel's Spider-Man, Insomniac brings the X-Men's most iconic mutant to life in a story-driven action game. The best there is. The best there ever will be.",
  "Gears of War: E-Day": "Return to the horrors of Emergence Day in this intense, harrowing prequel to the Gears of War saga. Witness the Locust Horde's first assault on humanity through the eyes of young Marcus Fenix and Dom Santiago, before they became battle-hardened veterans. Experience the terror of first contact as the Locust emerge from below, destroying cities and throwing humanity into chaos. Fight desperate last-stand battles through the streets of cities as civilization crumbles around you. The Coalition delivers visceral, cover-based combat at its finest with Unreal Engine 5's stunning visual fidelity \u2014 every bullet impact, every shattered wall, every brutal execution is rendered in breathtaking detail. The weight and impact of the Gnasher shotgun and Lancer assault rifle have never felt more devastating. A deeply emotional story explores the bonds of brotherhood forged in the crucible of war. Witness the birth of the COG and the desperate measures humanity took to survive. Welcome to E-Day.",
  "Mass Effect 5": "The next chapter in BioWare's beloved sci-fi saga continues, set in a galaxy still recovering from the Reaper War. A new hero rises to unite the fractured species of the galaxy against an emerging threat that could end all life. Discover never-before-seen worlds, from thriving alien civilizations to ancient ruins holding secrets of the Reapers' true origins. Build your crew from a diverse cast of characters, each with deep personal stories, loyalty missions, and romantic possibilities. Refined combat blends the tactical squad-based shooting of Mass Effect 3 with new mobility options including jetpacks, sliding, and enhanced biotics. Make choices that ripple across the galaxy and return in unexpected ways across the story. Beloved species and locations return alongside new alien races and unexplored systems. Deep character relationships are at the heart of the experience \u2014 your crew is your family, and their fates rest in your hands. The galaxy needs a new legend. That legend is you.",
};

// ─── Detailed game data (highlights, publisher) ───
const gameDetails = [
  { title: "Elden Ring", publisher: "Bandai Namco Entertainment", highlights: ["Massive open world with 6 distinct regions to explore freely", "Over 200 unique boss encounters and enemy types", "Deep RPG customization with 8 starting classes and hundreds of weapons", "Seamless multiplayer with cooperative and invasion mechanics", "George R.R. Martin's mythic world-building woven into every corner", "Multiple endings based on your choices throughout the journey"] },
  { title: "The Legend of Zelda: Breath of the Wild", publisher: "Nintendo", highlights: ["Vast open world with unprecedented freedom of exploration", "Innovative physics and chemistry engine for creative problem-solving", "Over 120 Shrine puzzles and 900 Korok Seeds to discover", "Dynamic weather and temperature systems affect gameplay", "Non-linear storytelling with multiple possible endings", "Masterful level design that rewards curiosity and experimentation"] },
  { title: "Cyberpunk 2077", publisher: "CD Projekt Red", highlights: ["Massive open-world Night City with six distinct districts", "Deep character customization with lifepaths that shape your story", "Branching narrative with multiple endings based on key choices", "Fluid first-person combat combining guns, melee, and hacking", "Stunning ray-traced visuals and immersive cyberpunk atmosphere", "Rich side content with meaningful stories and memorable characters"] },
  { title: "God of War Ragnar\u00f6k", publisher: "Sony Interactive Entertainment", highlights: ["Epic conclusion to the Norse saga with emotional storytelling", "Brutal combat with the Leviathan Axe and Blades of Chaos", "Nine stunning realms to explore, each with unique biomes", "Deep father-son dynamic between Kratos and Atreus", "Challenging boss battles including Norse gods and mythical creatures", "Accessibility features without compromising the core experience"] },
  { title: "Baldur's Gate 3", publisher: "Larian Studios", highlights: ["Based on Dungeons & Dragons 5th Edition ruleset", "Over 174 hours of cinematics and branching narratives", "11 playable races and 12 classes with infinite combinations", "Deep companion system with romance options and personal quests", "Turn-based combat with environmental interactions and verticality", "Nearly infinite replayability with choices that ripple through the story"] },
  { title: "Hogwarts Legacy", publisher: "Warner Bros. Games", highlights: ["Explore an incredibly detailed Hogwarts Castle and its grounds", "Learn and master over 30 spells with unique combat applications", "Brew potions, grow magical plants, and tame fantastic beasts", "Make moral choices that affect your character's path", "Engage in broomstick flying and magical beast racing", "Rich RPG systems with talent trees and gear customization"] },
  { title: "The Witcher 3: Wild Hunt", publisher: "CD Projekt Red", highlights: ["Massive open world with over 100 hours of content", "Morally complex choices with far-reaching consequences", "Deep character customization through skills, gear, and alchemy", "Memorable cast of characters with rich backstories", "Two award-winning expansions that rival full games", "Living world with dynamic events and monster contracts"] },
  { title: "Red Dead Redemption 2", publisher: "Rockstar Games", highlights: ["One of the most detailed open worlds ever created", "Cinematic storytelling with emotional character arcs", "Deep honor system that affects interactions and dialogue", "Extensive hunting, fishing, and crafting mechanics", "Dynamic AI with realistic daily routines and reactions", "Rich multiplayer component with Red Dead Online"] },
  { title: "Ghost of Tsushima", publisher: "Sony Interactive Entertainment", highlights: ["Stunning Japanese open world with poetic visual design", "Fluid katana combat with multiple stances for different enemies", "Stealth mechanics that make you feel like a true ninja", "Guiding Wind system replaces traditional waypoints", "Haiku, hot springs, and bamboo strikes for cultural immersion", "Engrossing Kurosawa-inspired cinematic filter mode"] },
  { title: "Final Fantasy XVI", publisher: "Square Enix", highlights: ["Action-oriented combat system with spectacular Eikon battles", "Dark fantasy narrative with mature themes and political intrigue", "Stunning real-time cinematics and visual spectacle", "Deep character-driven story following Clive Rosfield's journey", "Summonable Eikon abilities with devastating special moves", "Epic scale battles that push the limits of the PS5 hardware"] },
  { title: "Starfield", publisher: "Bethesda Softworks", highlights: ["Over 1,000 planets to explore across 100 star systems", "Deep ship customization from cockpit to cargo hold", "Compelling main story with multiple faction questlines", "Skill-based progression system with 5 skill categories", "Outpost building and resource management mechanics", "Classic Bethesda RPG freedom with space exploration"] },
  { title: "Palworld", publisher: "Pocketpair", highlights: ["Unique blend of creature collecting and survival crafting", "Over 100 Pals with distinct abilities and work skills", "Build automated bases with Pal labor systems", "Multiplayer co-op for up to 4 players", "Third-person shooter combat mechanics", "Open world with diverse biomes and hidden secrets"] },
  { title: "Dragon's Dogma 2", publisher: "Capcom", highlights: ["Intelligent Pawn system with cross-player learning AI", "Nine vocations with unique weapon skills and playstyles", "Massive monsters that can be climbed and scaled dynamically", "Seamless open world with emergent encounters", "Deep character and party customization options", "New and improved combat mechanics over the original"] },
  { title: "Helldivers 2", publisher: "Sony Interactive Entertainment", highlights: ["Intense cooperative third-person shooter gameplay", "Stratagem system with orbital strikes and support weapons", "Friendly fire enabled for hilarious and tense moments", "Dynamic mission objectives with procedural elements", "Cross-platform play between PS5 and PC", "Regular content updates with new enemies and equipment"] },
  { title: "Tekken 8", publisher: "Bandai Namco Entertainment", highlights: ["32 characters at launch with unique fighting styles", "Aggressive Heat System encourages offensive play", "Stunning Unreal Engine 5 graphics with destructible stages", "Deep combo system with Rage Arts and special moves", "Robust online modes with cross-play support", "Cinematic story mode continuing the Mishima saga"] },
  { title: "Final Fantasy VII Remake", publisher: "Square Enix", highlights: ["Faithful reimagining of the beloved PS1 classic", "Hybrid real-time/tactical combat system", "Expanded Midgar with new areas and story content", "Deep character progression with materia system", "Stunning visual presentation and emotional performances", "Side quests that flesh out the world and characters"] },
  { title: "Dark Souls III", publisher: "Bandai Namco Entertainment", highlights: ["Interconnected world design with clever shortcuts", "Over 20 challenging boss encounters", "Deep weapon arts system for combat variety", "Rich lore told through item descriptions and environment", "Competitive and cooperative multiplayer components", "Atmospheric level design with gothic and decaying beauty"] },
  { title: "Bloodborne", publisher: "Sony Interactive Entertainment", highlights: ["Gothic Victorian horror atmosphere with cosmic dread", "Aggressive combat with rally health recovery system", "Ingeniously connected world design with shortcuts", "Over 30 unique boss encounters of varying difficulty", "Chalice Dungeons for procedurally generated content", "Rich Lovecraftian lore and environmental storytelling"] },
  { title: "Monster Hunter: World", publisher: "Capcom", highlights: ["14 weapon types with unique moves and mechanics", "Living ecosystems with complex monster interactions", "Four-player cooperative hunting with scaling difficulty", "Deep armor and weapon crafting from monster materials", "Seasonal events with exclusive monsters and rewards", "Beautiful, detailed environments that feel alive"] },
  { title: "Metal Gear Solid V: The Phantom Pain", publisher: "Konami", highlights: ["Open-world stealth with unlimited tactical approaches", "Deep buddy system with unique companion abilities", "Base building and mother base management", "Complex mission structure with multiple outcomes", "Pioneering game design with emergent gameplay moments", "Cinematic storytelling and memorable characters"] },
  { title: "Death Stranding", publisher: "Sony Interactive Entertainment", highlights: ["Unique delivery simulation with deep traversal mechanics", "Asynchronous multiplayer building shared infrastructure", "Stunning landscapes with dynamic weather and time of day", "Celebrity cast including Norman Reedus and Mads Mikkelsen", "Thought-provoking narrative about connection in isolation", "Innovative social strand system connecting players"] },
  { title: "Persona 5", publisher: "Atlus", highlights: ["Stylish art direction and award-winning soundtrack", "Deep social simulation with calendar-based progression", "Turn-based combat with press-turn battle system", "Seven palace dungeons with unique themes and mechanics", "Rich character stories through confidant relationships", "Over 100 hours of content with New Game+ features"] },
  { title: "Devil May Cry 5", publisher: "Capcom", highlights: ["Three playable characters with distinct combat styles", "Deep style ranking system rewarding creative combat", "RE Engine delivers stunning 60fps action", "Over 40 enemy types and challenging boss encounters", "New game modes including Bloody Palace", "Satisfying combat depth with hundreds of moves"] },
  { title: "Resident Evil 4 Remake", publisher: "Capcom", highlights: ["Masterful reimagining of the 2005 survival horror classic", "Over-the-shoulder combat with modern controls", "Intelligent AI enemies with dynamic behavior patterns", "Expanded story content and character development", "Mercenaries mode for high-score arcade action", "RE Engine delivers photorealistic horror visuals"] },
  { title: "Street Fighter 6", publisher: "Capcom", highlights: ["Three distinct gameplay modes for all skill levels", "Drive System for offensive and defensive options", "Cross-platform play with rollback netcode", "18 fighters at launch with diverse fighting styles", "World Tour single-player RPG adventure mode", "Deep training mode with frame data and replay analysis"] },
  { title: "Mortal Kombat 1", publisher: "Warner Bros. Games", highlights: ["Rebooted timeline with reimagined character origins", "Kameo Fighter system for expanded combat options", "Story mode with cinematic presentation", "Over 40 characters including DLC guest fighters", "Invasions mode with seasonal content", "Crystal-clear 60fps gameplay with detailed graphics"] },
  { title: "NBA 2K24", publisher: "2K Sports", highlights: ["Authentic NBA simulation with real teams and players", "MyCAREER mode with city exploration", "MyTEAM card collection with online competition", "The W mode featuring WNBA players", "Updated gameplay mechanics with ProPLAY technology", "Cross-play support for select online modes"] },
  { title: "FC 24", publisher: "EA Sports", highlights: ["HyperMotion V technology for realistic player movement", "Ultimate Team with deep squad building", "Career mode with improved transfer logic", "VOLTA Football returns with street soccer", "Over 19,000 licensed players and 700+ teams", "Cross-play across multiple platforms"] },
  { title: "Gran Turismo 7", publisher: "Sony Interactive Entertainment", highlights: ["Over 400 cars with detailed interiors", "34 track locations with 90+ layout variations", "Dynamic time and weather systems", "Deep tuning and customization options", "Campaign mode with Cafe menus and missions", "PS VR2 support for immersive racing"] },
  { title: "Forza Motorsport", publisher: "Xbox Game Studios", highlights: ["Over 500 cars with realistic physics simulation", "Dynamic time of day and weather on every track", "Tire and fuel management strategy", "Deep car upgrade and tuning system", "Ray-traced visuals at 60fps on Xbox Series X", "Competitive multiplayer with driver ratings"] },
  { title: "Alan Wake 2", publisher: "Epic Games Publishing", highlights: ["Two protagonists with interconnected campaigns", "Remedy's signature live-action storytelling", "Survival horror with psychological themes", "Stunning Northlight engine graphics", "Metabridge system for case-solving", "Expansion content with Night Springs and The Lake House"] },
  { title: "Star Wars Jedi: Survivor", publisher: "Electronic Arts", highlights: ["Expanded lightsaber combat with five stances", "Larger open-world areas with more freedom", "Deep customization for Cal's appearance and skills", "Compelling story bridging the gap between trilogies", "Challenging boss battles against Inquisitors", "Improved performance and fast travel system"] },
  { title: "Minecraft", publisher: "Mojang Studios", highlights: ["Infinite procedurally generated worlds", "Creative mode with unlimited building potential", "Survival mode with resource gathering and combat", "Cross-platform play with friends", "Vast modding community and custom servers", "Regular content updates with new biomes and mobs"] },
  { title: "Fortnite", publisher: "Epic Games", highlights: ["Free-to-play battle royale with 100-player matches", "Unique building mechanics for defensive strategy", "Regular content updates with themed seasons", "Crossover events with major franchises", "Creative mode for custom game creation", "Save the World cooperative PvE campaign"] },
  { title: "Call of Duty: Modern Warfare III", publisher: "Activision", highlights: ["Cinematic campaign continuing MWII storyline", "Multiplayer with 16 remastered MW2 maps", "Open combat missions with tactical freedom", "Zombies mode with extraction gameplay", "Gunsmith customization with aftermarket parts", "Cross-platform play and progression"] },
  { title: "Grand Theft Auto V", publisher: "Rockstar Games", highlights: ["Three interwoven character storylines", "Massive open-world Los Santos and Blaine County", "GTA Online with constant content updates", "Heist missions with cooperative planning", "Deep vehicle customization and properties", "Stunning visuals on PC and current-gen consoles"] },
  { title: "League of Legends", publisher: "Riot Games", highlights: ["Over 160 unique champions with distinct abilities", "Strategic 5v5 MOBA gameplay", "Competitive ranked mode with tiers and divisions", "Regular balance updates and new champion releases", "Thriving esports scene with global tournaments", "Free-to-play with cosmetic-only monetization"] },
  { title: "Dota 2", publisher: "Valve Corporation", highlights: ["Over 120 heroes with unique abilities and roles", "Deep item system with 200+ items and upgrades", "Free-to-play with all heroes unlocked", "The International tournament with massive prize pools", "Custom games and arcade mode", "Complex mechanics requiring high skill ceiling"] },
  { title: "Counter-Strike 2", publisher: "Valve Corporation", highlights: ["Source 2 engine upgrade with improved graphics", "Tactical 5v5 competitive gameplay", "Sub-tick netcode for precise hit registration", "Classic dust2, inferno, and mirage return", "Skin economy with millions of items", "Premier mode with CS rating system"] },
  { title: "Valorant", publisher: "Riot Games", highlights: ["Tactical 5v5 FPS with unique agent abilities", "Precise gunplay with spray patterns and recoil", "20+ agents with distinct roles and abilities", "Competitive mode with rank progression", "Esports ecosystem with global tournaments", "Anti-cheat with Vanguard protection system"] },
  { title: "Overwatch 2", publisher: "Blizzard Entertainment", highlights: ["40+ heroes with unique abilities and playstyles", "5v5 format for faster-paced matches", "Role queue and open queue competitive modes", "Frequent seasonal events and content updates", "Cross-platform play and progression", "Arcade modes including Mystery Heroes and Deathmatch"] },
  { title: "Apex Legends", publisher: "Electronic Arts", highlights: ["24 playable legends with unique abilities", "Squad-based 3v3 battle royale gameplay", "Innovative ping system for no-voice communication", "Seasonal battle pass with new content", "Ranked mode with skill-based matchmaking", "Regular weapon balance and meta updates"] },
  { title: "Warframe", publisher: "Digital Extremes", highlights: ["30+ Warframes with unique ability kits", "Fast-paced parkour movement system", "Deep modding for weapons and Warframes", "Open-world landscapes on different planets", "PvE cooperative missions with full squads", "Regular major updates with new content"] },
  { title: "Path of Exile", publisher: "Grinding Gear Games", highlights: ["Massive passive skill tree with 1,500+ nodes", "Deep socket-linked gem system", "Endgame mapping with the Atlas of Worlds", "Challenge leagues with unique mechanics every 3 months", "Free-to-play with cosmetic-only monetization", "Trading economy with currency-based barter system"] },
  { title: "Lost Ark", publisher: "Amazon Games", highlights: ["Isometric action MMO with fluid combat", "15 classes with unique playstyles", "Raids with complex mechanics and teamwork", "Stronghold island management system", "PvP arenas with competitive ranked play", "Beautiful visuals with top-down perspective"] },
  { title: "New World", publisher: "Amazon Games", highlights: ["Player-driven economy with crafting focus", "Large-scale 50v50 PvP wars", "3 faction system with territory control", "Action-oriented combat with targeting", "Expeditions for 5-player PvE content", "Beautifully rendered 17th century setting"] },
  { title: "Final Fantasy XIV", publisher: "Square Enix", highlights: ["Expansive main scenario quest spanning 10+ years", "20 combat jobs with unique playstyles", "Crafting and gathering with their own progression", "Housing system with furniture customization", "Active community with friendly player base", "Regular major patches every 4 months"] },
  { title: "World of Warcraft", publisher: "Blizzard Entertainment", highlights: ["Rich Warcraft lore spanning 20+ years", "Over 30 million unique character classes", "Massive open world with hundreds of zones", "Raids and dungeons for group PvE content", "PvP battlegrounds and arenas", "World of Warcraft Classic available"] },
  { title: "Halo Infinite", publisher: "Xbox Game Studios", highlights: ["Open-world campaign sections with freedom", "Classic Halo gameplay with modern mechanics", "Free-to-play multiplayer with battle pass", "Deep weapon sandbox with unique equipment", "Forge mode for custom map creation", "Competitive ranked mode with 4v4 action"] },
  { title: "Assassin's Creed: Mirage", publisher: "Ubisoft", highlights: ["Return to stealth-focused parkour gameplay", "Dense, vertical city of Baghdad to explore", "Assassin focus tools and costumes", "Streamlined RPG elements and skill trees", "Historical setting with authentic architecture", "Shorter, focused campaign experience"] },
  { title: "Spider-Man 2", publisher: "Sony Interactive Entertainment", highlights: ["Two playable Spider-Men with unique abilities", "Instant web-swinging with no loading screens", "Expanded New York with Brooklyn and Queens", "Venom abilities for Peter Parker", "Symbiote storyline and character evolution", "Improved combat with web wings and gadgets"] },
];

async function main() {
  await connectDB();

  if (mode === "posters") {
    let count = 0;
    for (const [title, data] of Object.entries(posterFixes)) {
      const game = await Game.findOne({ title });
      if (!game) { console.log(`NOT FOUND: ${title}`); continue; }
      await Game.findByIdAndUpdate(game._id, { $set: { poster: data.poster, screenshots: data.screenshots } });
      console.log(`\u2713 ${title}`);
      count++;
    }
    console.log(`\nUpdated ${count} games`);
  }

  if (mode === "descriptions") {
    let count = 0;
    for (const [title, description] of Object.entries(descriptions)) {
      const game = await Game.findOne({ title });
      if (!game) { console.log(`NOT FOUND: ${title}`); continue; }
      const existing = game.screenshots || [];
      let screenshots = [...existing];
      if (screenshots.length === 0 && game.poster) screenshots = [game.poster];
      if (screenshots.length === 1 && game.poster && !screenshots.includes(game.poster)) screenshots.unshift(game.poster);
      await Game.findByIdAndUpdate(game._id, { $set: { description, screenshots } });
      console.log(`\u2713 ${title}`);
      count++;
    }
    console.log(`\nUpdated ${count} games`);
  }

  if (mode === "details") {
    let updated = 0;
    for (const data of gameDetails) {
      const result = await Game.findOneAndUpdate(
        { title: data.title },
        { $set: { publisher: data.publisher, highlights: data.highlights } },
        { new: true }
      );
      if (result) {
        console.log(`\u2713 ${result.title}`);
        updated++;
      } else {
        console.log(`\u2717 ${data.title} \u2014 not found`);
      }
    }
    console.log(`\nUpdated ${updated}/${gameDetails.length} games`);
  }

  process.exit(0);
}

main();
