import "dotenv/config";
import mongoose from "mongoose";
import Game from "../models/Game.js";
import connectDB from "../config/database.js";

const newGames = [
  {
    title: "Grand Theft Auto VI",
    description: "The most anticipated game of the decade finally arrives. Return to Vice City in this massive open-world crime epic that pushes gaming to new heights. Play as Lucia and Jason in a modern-day Bonnie and Clyde story across the sprawling state of Leonida. Experience unprecedented levels of detail, dynamic world events, improved combat mechanics, and the most immersive open world ever created. With Rockstar's signature storytelling, cutting-edge graphics, and infinite emergent gameplay, GTA VI redefines what video games can achieve.",
    director: "Sam Houser",
    cast: ["Rockstar Games"],
    genre: ["Action", "Adventure", "Crime"],
    releaseDate: new Date("2025-09-15"),
    duration: 150,
    language: "English",
    country: "USA",
    poster: "https://upload.wikimedia.org/wikipedia/en/2/2c/Grand_Theft_Auto_VI_cover_art.jpg",
    featured: true,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Monster Hunter Wilds",
    description: "Hunt colossal monsters in a breathtaking open world where ecosystems evolve in real-time. Master 14 weapon types, track monsters through dynamic weather systems, and experience seamless co-op hunting like never before. The environments react to your actions — changing seasons alter terrain, monster behavior, and available resources. With cross-platform play, improved mount mechanics, and the most ambitious monster roster in series history, Wilds is the ultimate hunting experience.",
    director: "Ryozo Tsujimoto",
    cast: ["Capcom"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2025-02-28"),
    duration: 120,
    language: "English",
    country: "Japan",
    poster: "https://cdn.akamai.steamstatic.com/steam/apps/2246340/header.jpg",
    featured: true,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Doom: The Dark Ages",
    description: "Rip and tear through a medieval fantasy world where demons have conquered the kingdom. As the legendary Slayer, wield brutal dark age weaponry — from enchanted swords to demonic crossbows — in visceral first-person combat. Explore sprawling gothic castles, hellish dungeons, and corrupted forests. With id Software's signature fluid combat, devastating finishers, and a haunting heavy metal soundtrack, this prequel to the modern Doom games delivers relentless action.",
    director: "Hugo Martin",
    cast: ["id Software"],
    genre: ["Action", "Horror", "Fantasy"],
    releaseDate: new Date("2025-05-13"),
    duration: 20,
    language: "English",
    country: "USA",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/8d/Doom_The_Dark_Ages_cover.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Death Stranding 2: On the Beach",
    description: "Continue Sam Bridges' journey in a world struggling to reconnect. Navigate hauntingly beautiful landscapes, face new supernatural threats called the 'Beach,' and uncover the mysteries of extinction. With expanded traversal mechanics, improved combat, deeper social strand systems, and Hideo Kojima's signature storytelling, the sequel builds on everything that made the original unique. Featuring stunning visuals, emotional performances, and thought-provoking themes.",
    director: "Hideo Kojima",
    cast: ["Kojima Productions"],
    genre: ["Action", "Adventure", "Sci-Fi"],
    releaseDate: new Date("2025-06-26"),
    duration: 60,
    language: "English",
    country: "Japan",
    poster: "https://upload.wikimedia.org/wikipedia/en/6/6f/Death_Stranding_2_cover_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Assassin's Creed Shadows",
    description: "Feudal Japan comes alive in this breathtaking Assassin's Creed adventure. Play as Naoe, a shinobi assassin, and Yasuke, the legendary African samurai, in a sprawling open world. Master stealth techniques, engage in visceral katana combat, and explore a beautifully rendered 16th-century Japan. Dynamic seasons change gameplay, historical figures shape your journey, and the legendary Assassin vs. Templar conflict unfolds in an entirely new region.",
    director: "Jonathan Dumont",
    cast: ["Ubisoft Quebec"],
    genre: ["Action", "Adventure", "History"],
    releaseDate: new Date("2025-03-20"),
    duration: 80,
    language: "English",
    country: "Canada",
    poster: "https://cdn.akamai.steamstatic.com/steam/apps/3159330/header.jpg",
    featured: true,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Avowed",
    description: "Explore the living world of Eora in this first-person RPG from the creators of Pillars of Eternity. As an envoy of the Aedyr Empire, investigate a mysterious plague spreading through the living lands. Wield swords, spells, and firearms in fluid combat, make choices that reshape the world, and uncover secrets that challenge your understanding of reality. With Obsidian's hallmark reactive storytelling and deep RPG systems, Avowed delivers choice and consequence.",
    director: "Carrie Patel",
    cast: ["Obsidian Entertainment"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2025-02-18"),
    duration: 50,
    language: "English",
    country: "USA",
    poster: "https://upload.wikimedia.org/wikipedia/en/5/54/Avowed_cover_art.png",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Metroid Prime 4: Beyond",
    description: "Samus Aran returns in a brand-new first-person adventure that pushes the boundaries of the Metroid Prime formula. Explore alien worlds with stunning detail, engage in precision combat, and solve environmental puzzles using upgraded abilities. The iconic visor system returns with new scanning modes, while improved movement mechanics and intense boss battles deliver classic Metroid action. A masterful blend of exploration, combat, and atmosphere.",
    director: "Retro Studios",
    cast: ["Retro Studios", "Nintendo"],
    genre: ["Action", "Adventure", "Sci-Fi"],
    releaseDate: new Date("2025-08-06"),
    duration: 30,
    language: "English",
    country: "USA",
    poster: "https://upload.wikimedia.org/wikipedia/en/7/7c/Metroid_Prime_4_box_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Ghost of Yotei",
    description: "Set 300 years after Ghost of Tsushima, a new Ghost rises in the shadow of Mount Yotei in feudal Japan. Play as Atsu, a warrior haunted by her past, wielding new weapons and tactics in a vast northern frontier. Dynamic weather and seasons affect gameplay, new ghost weapons expand tactical options, and a gripping story of vengeance and redemption unfolds against stunning landscapes. Sucker Punch delivers another open-world masterpiece.",
    director: "Nate Fox",
    cast: ["Sucker Punch Productions"],
    genre: ["Action", "Adventure", "Drama"],
    releaseDate: new Date("2025-10-24"),
    duration: 40,
    language: "English",
    country: "USA",
    poster: "https://upload.wikimedia.org/wikipedia/en/3/3b/Ghost_of_Yotei_cover.jpg",
    featured: true,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Borderlands 4",
    description: "The signature looter-shooter returns with billions of guns, mayhem-fueled combat, and a brand-new Vault Hunter roster. Explore a never-before-seen planet, unleash devastating action skills, and battle through hordes of psychos in drop-in/drop-out co-op. New elemental damage systems, vehicle combat enhancements, and the most chaotic skill trees yet make this the biggest Borderlands adventure. Mayhem awaits on the frontier.",
    director: "Randy Pitchford",
    cast: ["Gearbox Software"],
    genre: ["Action", "Adventure", "Sci-Fi"],
    releaseDate: new Date("2025-09-30"),
    duration: 45,
    language: "English",
    country: "USA",
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4b/Borderlands_4_cover_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Sid Meier's Civilization VII",
    description: "Lead your civilization from ancient times to the space age in the next evolution of the legendary strategy franchise. New gameplay systems include dynamic diplomacy, enhanced warfare tactics, and deeper cultural development paths. Choose from a diverse roster of leaders, each with unique abilities and agendas. Build your empire through science, culture, military might, or economic dominance in the most ambitious Civilization game yet.",
    director: "Ed Beach",
    cast: ["Firaxis Games"],
    genre: ["Action", "War", "History"],
    releaseDate: new Date("2025-02-11"),
    duration: 1,
    language: "English",
    country: "USA",
    poster: "https://cdn.akamai.steamstatic.com/steam/apps/1295660/header.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Split Fiction",
    description: "Embark on a genre-defying co-op adventure where two writers, trapped in their own stories, must navigate shifting worlds blending sci-fi and fantasy. From Hazelight Studios, the creators of It Takes Two, comes an innovative split-screen experience. Solve creative puzzles, overcome dynamic obstacles, and experience a heartfelt story about creativity and friendship. Unique dual-character mechanics require constant cooperation in this boundary-pushing adventure.",
    director: "Josef Fares",
    cast: ["Hazelight Studios"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2025-03-06"),
    duration: 18,
    language: "English",
    country: "Sweden",
    poster: "https://cdn.akamai.steamstatic.com/steam/apps/2006890/header.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Fable",
    description: "The legendary RPG series returns with a brand-new adventure filled with British humor, moral choices, and magical mayhem. Explore the land of Albion like never before — a sprawling fantasy world where your actions shape your character, your reputation, and the world itself. Wield magic and melee combat, build relationships, own property, and become the hero — or villain — you were meant to be. Playground Games brings the beloved series into a new era.",
    director: "Playground Games",
    cast: ["Playground Games"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2025-10-08"),
    duration: 50,
    language: "English",
    country: "UK",
    poster: "https://upload.wikimedia.org/wikipedia/en/8/8f/Fable_2025_cover_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "The First Berserker: Khazan",
    description: "A hardcore action RPG set in the Dungeon Fighter Online universe, featuring punishing combat and deep character customization. As Khazan, the legendary berserker framed for treason, fight through brutal battlefields with precision-based combat mechanics. Master different weapon styles, parry enemy attacks, and unleash devastating skills. With stunning cel-shaded visuals, challenging boss encounters, and a gripping revenge story, this is a must-play for action RPG fans.",
    director: "Neople",
    cast: ["Neople", "Nexon"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2025-03-27"),
    duration: 40,
    language: "English",
    country: "South Korea",
    poster: "https://upload.wikimedia.org/wikipedia/en/1/1e/The_First_Berserker_Khazan_cover.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Atomfall",
    description: "Survive in a British post-apocalyptic open world set five years after the Windscale nuclear disaster. Scavenge resources, craft weapons, and uncover a conspiracy in a beautifully radioactive English countryside. Investigate mysterious signals, navigate irradiated zones, and face mutated creatures and desperate survivors. With its unique British setting, immersive survival mechanics, and branching narrative, Atomfall offers a fresh take on the post-apocalyptic genre.",
    director: "Ben Fisher",
    cast: ["Rebellion Developments"],
    genre: ["Action", "Adventure", "Sci-Fi"],
    releaseDate: new Date("2025-03-25"),
    duration: 30,
    language: "English",
    country: "UK",
    poster: "https://upload.wikimedia.org/wikipedia/en/b/b6/Atomfall_cover_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Elden Ring Nightreign",
    description: "A standalone co-op survival experience set in the Elden Ring universe. Face the Nightlord across three procedurally generated days, gaining strength by defeating bosses and discovering powerful equipment. Choose from unique classes with specialized abilities, master new combat mechanics including mounts and aerial attacks, and survive against the relentless night. Faithful to the signature challenge while introducing roguelike elements, this is a fresh way to experience the Lands Between.",
    director: "Hidetaka Miyazaki",
    cast: ["FromSoftware"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2025-05-30"),
    duration: 60,
    language: "English",
    country: "Japan",
    poster: "https://upload.wikimedia.org/wikipedia/en/1/1b/Elden_Ring_Nightreign_cover.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Mafia: The Old Country",
    description: "Experience the origins of organized crime in 1900s Sicily in this gritty open-world crime drama. Build your criminal empire from the ground up, earn respect through brutal enforcement, and navigate the complex codes of honor in a beautifully realized historical setting. With Hangar 13's signature storytelling, authentic period detail, and cinematic mission design, this prequel delivers a compelling mafia saga rooted in tradition and betrayal.",
    director: "Krzysztof Zięba",
    cast: ["Hangar 13"],
    genre: ["Action", "Adventure", "Crime"],
    releaseDate: new Date("2025-12-04"),
    duration: 30,
    language: "English",
    country: "USA",
    poster: "https://upload.wikimedia.org/wikipedia/en/1/11/Mafia_The_Old_Country_cover.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Like a Dragon: Pirate Yakuza in Hawaii",
    description: "Set sail for adventure in this wild spin-off that turns the Yakuza series on its head. Play as Goro Majima, now an amnesiac pirate captain, exploring the seas around Hawaii in naval combat. Switch between brutal pirate-style brawling and traditional Majima combat styles. Build your pirate crew, manage your ship, and uncover treasure and conspiracy on tropical islands. With RGG Studio's signature blend of serious drama and absurd humor, this is Yakuza like you've never seen it.",
    director: "Ryosuke Horii",
    cast: ["Ryu Ga Gotoku Studio"],
    genre: ["Action", "Adventure", "Comedy"],
    releaseDate: new Date("2025-02-20"),
    duration: 50,
    language: "English",
    country: "Japan",
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4b/Like_a_Dragon_Pirate_Yakuza_cover.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Clair Obscur: Expedition 33",
    description: "A stunning turn-based RPG set in a world where a mysterious Paintress erases color and life each year. Lead Expedition 33 on a desperate mission to stop her, exploring a painterly universe where beauty and danger intertwine. Master unique combat mechanics blending turn-based strategy with real-time dodges and counters. With its breathtaking Belle Époque-inspired art style, emotional narrative, and innovative hybrid combat, this is one of the most visually striking RPGs ever made.",
    director: "Guillaume Broche",
    cast: ["Sandfall Interactive"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2025-04-24"),
    duration: 40,
    language: "English",
    country: "France",
    poster: "https://upload.wikimedia.org/wikipedia/en/9/9f/Clair_Obscur_Expedition_33_cover.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "South of Midnight",
    description: "Immerse yourself in the haunted American Deep South in this third-person action-adventure from Compulsion Games. Play as Hazel, a weaver who can mend broken spirits and unravel supernatural curses. Explore a beautifully grotesque world inspired by Southern Gothic folklore, battle twisted creatures, and uncover family secrets. With its unique art style blending stop-motion animation with modern graphics, rich storytelling, and meaningful combat, South of Midnight is a journey through myth and memory.",
    director: "Compulsion Games",
    cast: ["Compulsion Games"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2025-07-08"),
    duration: 20,
    language: "English",
    country: "Canada",
    poster: "https://upload.wikimedia.org/wikipedia/en/d/d5/South_of_Midnight_cover.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "The Witcher IV",
    description: "The next epic chapter in the Witcher saga, featuring Ciri as the protagonist. Hunt monsters across a vast continent transformed by war and political upheaval. Master new magical abilities, craft powerful witcher gear, and make morally complex choices that reshape the world. With REDengine's next-gen technology, deeply reactive storytelling, and expanded open-world systems, The Witcher IV sets a new standard for narrative-driven RPGs. A legend is reborn.",
    director: "Sebastian Kalemba",
    cast: ["CD Projekt Red"],
    genre: ["Action", "Adventure", "Fantasy"],
    releaseDate: new Date("2026-10-01"),
    duration: 120,
    language: "English",
    country: "Poland",
    poster: "https://upload.wikimedia.org/wikipedia/en/a/a1/The_Witcher_IV_cover_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Marvel's Wolverine",
    description: "Unleash your animal instincts in this visceral third-person action game from Insomniac Games. Play as Logan — the best there is at what he does — in a mature, emotionally charged narrative. Tear through enemies with adamantium claws, experience regenerative healing in gameplay, and explore locations from dive bars to secret Weapon X facilities. With the same care and quality that defined Marvel's Spider-Man, Insomniac brings the X-Men's most iconic mutant to life.",
    director: "Brian Horton",
    cast: ["Insomniac Games"],
    genre: ["Action", "Adventure", "Drama"],
    releaseDate: new Date("2026-09-01"),
    duration: 30,
    language: "English",
    country: "USA",
    poster: "https://upload.wikimedia.org/wikipedia/en/3/35/Marvel%27s_Wolverine_cover_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Gears of War: E-Day",
    description: "Return to the horrors of Emergence Day in this intense prequel to the Gears of War saga. Witness the Locust Horde's first assault on humanity through the eyes of young Marcus Fenix and Dom Santiago. Experience the terror of the first contact, desperate last stands, and the birth of the COG. With Unreal Engine 5's stunning fidelity, visceral cover-based combat, and the series' signature emotional weight, E-Day is a harrowing return to the franchise's roots.",
    director: "Matt Searcy",
    cast: ["The Coalition"],
    genre: ["Action", "War", "Sci-Fi"],
    releaseDate: new Date("2026-06-15"),
    duration: 18,
    language: "English",
    country: "Canada",
    poster: "https://upload.wikimedia.org/wikipedia/en/2/27/Gears_of_War_E-Day_cover_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
  {
    title: "Mass Effect 5",
    description: "The next chapter in BioWare's beloved sci-fi saga continues with a new hero and a galaxy in turmoil. Discover new worlds, build your crew, and make choices that ripple across the stars. With refined combat blending classic Mass Effect gunplay with new mobility options, deep character relationships, and the return of beloved species and locations, this is the Mass Effect you've been waiting for. The galaxy needs a new legend — and that legend is you.",
    director: "Michael Gamble",
    cast: ["BioWare"],
    genre: ["Action", "Adventure", "Sci-Fi"],
    releaseDate: new Date("2026-12-01"),
    duration: 80,
    language: "English",
    country: "Canada",
    poster: "https://upload.wikimedia.org/wikipedia/en/2/2d/Mass_Effect_5_cover_art.jpg",
    featured: false,
    isActive: true,
    addedBy: "system",
  },
];

const steamIDs = {
  "Monster Hunter Wilds": 2246340,
  "Assassin's Creed Shadows": 3159330,
  "Sid Meier's Civilization VII": 1295660,
  "Split Fiction": 2006890,
};

async function main() {
  try {
    await connectDB();
    let count = 0;
    for (const game of newGames) {
      const existing = await Game.findOne({ title: game.title });
      if (existing) {
        console.log(`Skipped (exists): ${game.title}`);
        continue;
      }
      await Game.create(game);
      console.log(`Added: ${game.title}`);
      count++;
    }
    console.log(`\nInserted ${count} new games (${newGames.length - count} already existed)`);
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

main();
