import "dotenv/config";
import mongoose from "mongoose";
import Movie from "../models/Movie.js";
import connectDB from "../config/database.js";

// Sample game data - 51 popular games with enhanced descriptions and images
const sampleMovies = [
  { title: "Elden Ring", description: "A masterpiece collaboration between FromSoftware and George R.R. Martin featuring a vast open-world filled with mystery and danger. Explore the Lands Between freely, engage in challenging combat with intricate boss battles, and uncover multiple branching storylines that reshape the world. Experience the perfect blend of beautiful landscapes, dark fantasy atmosphere, and rewarding exploration with deep RPG mechanics.", director: "Hidetaka Miyazaki", cast: ["FromSoftware"], genre: ["Action", "Adventure", "Fantasy"], releaseDate: new Date("2022-02-25"), duration: 100, language: "English", country: "Japan", poster: "https://cdn2.unrealengine.com/eol-eldenring-sonycapture-1920x1080-1920x1080-5e9e61e2e5c2.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "The Legend of Zelda: Breath of the Wild", description: "A revolutionary open-world adventure that completely redefined the action-adventure genre with unprecedented freedom. Break free from linear gameplay, solve environmental puzzles creatively, and tackle massive dungeons in any order you choose. Discover countless secrets, master combat mechanics, and experience one of gaming's greatest achievements with breathtaking artwork and innovative gameplay systems.", director: "Eiji Aonuma", cast: ["Nintendo"], genre: ["Adventure", "Action", "Fantasy"], releaseDate: new Date("2017-03-03"), duration: 80, language: "English", country: "Japan", poster: "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Cyberpunk 2077", description: "Immerse yourself in Night City, a sprawling metropolis of 2077 where technology and humanity collide. Create your own character and navigate a rich, branching narrative filled with moral choices that impact your world. Experience next-gen graphics, fast-paced combat, hacking gameplay, and a soundtrack that captures the essence of a dystopian future.", director: "Adam Badowski", cast: ["CD Projekt Red"], genre: ["Action", "Adventure", "Sci-Fi"], releaseDate: new Date("2020-12-10"), duration: 120, language: "English", country: "Poland", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "God of War Ragnarök", description: "The epic conclusion to Kratos' Norse mythology saga combines brutal combat, emotional storytelling, and jaw-dropping cinematics. Travel through realms to prevent Ragnarok while strengthening your bond with Atreus. Master devastating combat combinations, wield powerful weapons, and face mythological beings in this stunning PlayStation exclusive.", director: "Eric Williams", cast: ["Santa Monica Studio"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2022-11-09"), duration: 50, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/2322010/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Baldur's Gate 3", description: "Based on Dungeons & Dragons 5th Edition rules, this epic RPG offers unparalleled freedom with meaningful choices that shape your adventure. Join a party of companions with their own compelling stories, engage in strategic turn-based combat, and explore multiple interconnected narratives. With hundreds of hours of content and nearly infinite replayability, every decision matters in this masterpiece.", director: "Swen Vincke", cast: ["Larian Studios"], genre: ["Adventure", "Fantasy", "Drama"], releaseDate: new Date("2023-08-03"), duration: 150, language: "English", country: "Belgium", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Hogwarts Legacy", description: "Create your own witch or wizard and experience life in 1800s Hogwarts School of Witchcraft and Wizardry. Learn spells, build friendships, and uncover a sinister plot threatening the magical world. Explore the castle and surrounding grounds in stunning detail, discover hidden secrets, and engage in magical duels while immersing yourself in the beloved Harry Potter universe.", director: "David Holmes", cast: ["Avalanche Software"], genre: ["Adventure", "Fantasy", "Drama"], releaseDate: new Date("2023-02-10"), duration: 100, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "The Witcher 3: Wild Hunt", description: "Play as Geralt of Rivia, a master monster hunter, in this massive open-world RPG brimming with politics, magic, and moral complexity. Hunt dangerous creatures while engaging with memorable characters and intricate storylines that branch based on your choices. Stunning visuals, visceral combat, and legendary expansions make this one of gaming's greatest achievements.", director: "Adam Badowski", cast: ["CD Projekt Red"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2015-05-19"), duration: 100, language: "English", country: "Poland", poster: "https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Red Dead Redemption 2", description: "Experience an outlaw's life in the dying days of the Old West with unparalleled storytelling and world immersion. Play as Arthur Morgan and navigate the van der Linde gang's complex dynamics while exploring a massive, living world filled with secrets and side adventures. Cinematic missions, realistic mechanics, and emotional character development create an unforgettable narrative.", director: "Dan Houser", cast: ["Rockstar Games"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2018-10-26"), duration: 60, language: "English", country: "USA", poster: "https://www.rockstargames.com/reddeadredemption2/dist/img/hero-4e59f5df.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Ghost of Tsushima", description: "Become a legendary samurai warrior defending Tsushima Island during the Mongol invasion of 13th-century Japan. Master the way of the sword with fluid combat mechanics and stunning visual design that captures the essence of Japanese cinema. Explore beautiful landscapes, engage in emotional storytelling, and face increasingly dangerous enemies in this PlayStation masterpiece.", director: "Jason Connell", cast: ["Sucker Punch Productions"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2020-07-17"), duration: 30, language: "English", country: "USA", poster: "https://www.gstatic.com/tv/thumb/tvBanners/16627854/p16627854_b_v13_af.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Final Fantasy XVI", description: "Follow Clive Rosfield's epic journey across Valisthea in this action-packed Final Fantasy adventure featuring summonable magical beasts called Eikon. Engage in thrilling real-time combat, wield devastating spells and abilities, and uncover a deep narrative exploring power, destiny, and the cost of war. With innovative gameplay systems and breathtaking visuals, this is a stunning entry in the franchise.", director: "Hiroshi Takai", cast: ["Square Enix"], genre: ["Action", "Adventure", "Fantasy"], releaseDate: new Date("2023-06-22"), duration: 50, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/2515020/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Starfield", description: "Explore the cosmos in this expansive space RPG where you create your own astronaut and venture into the unknown. Build your spaceship, recruit companions, engage in space combat, and uncover mysteries across hundreds of planets. With deep character customization, faction quests, and the freedom to chart your own course, space exploration has never been more immersive.", director: "Todd Howard", cast: ["Bethesda Game Studios"], genre: ["Action", "Adventure", "Sci-Fi"], releaseDate: new Date("2023-09-06"), duration: 150, language: "English", country: "USA", poster: "https://upload.wikimedia.org/wikipedia/en/5/52/Starfield_cover.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Palworld", description: "Catch, train, and battle adorable Pal creatures in this action-packed adventure combining creature collection with real-time combat. Build your base, farm resources, engage in raids with friends, and uncover the mysteries of the Pal world. With unique creature designs, intense battles, and cooperative gameplay, this indie sensation offers endless fun.", director: "Masaya Uchida", cast: ["Pocketpair"], genre: ["Action", "Adventure", "Fantasy"], releaseDate: new Date("2024-01-19"), duration: 80, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Dragon's Dogma 2", description: "Battle colossal monsters with intelligent AI pawns who adapt to your tactics and support your adventure. Explore a dynamic world filled with emerging threats, discover powerful vocations to master, and engage in exhilarating combat against epic foes. With seamless multiplayer features and rewarding action mechanics, monster hunting reaches new heights.", director: "Hideaki Itsuno", cast: ["Capcom"], genre: ["Action", "Adventure", "Fantasy"], releaseDate: new Date("2024-03-22"), duration: 120, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/2054970/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Helldivers 2", description: "Lead elite Helldivers soldiers in cooperative warfare against alien bug hordes threatening managed planets. Work strategically with teammates, manage resources, call in orbital support, and complete dangerous missions across hostile worlds. This action-packed multiplayer shooter demands teamwork, communication, and tactical thinking for survival.", director: "Johan Pilestedt", cast: ["Arrowhead Game Studios"], genre: ["Action", "Sci-Fi", "War"], releaseDate: new Date("2024-02-08"), duration: 20, language: "English", country: "Sweden", poster: "https://cdn.akamai.steamstatic.com/steam/apps/553850/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Tekken 8", description: "Master complex fighting game mechanics in this technical 3D fighter featuring beloved characters and newcomers. Execute devastating combos, learn frame data, engage in cinematic super moves, and dominate online ranked matches or story modes. With gorgeous graphics and deep gameplay systems, Tekken 8 sets a new standard for fighting games.", director: "Katsuhiro Harada", cast: ["Bandai Namco"], genre: ["Action", "Sport", "Drama"], releaseDate: new Date("2024-01-26"), duration: 12, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1778820/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Final Fantasy VII Remake", description: "Experience Cloud Strife's legendary story reimagined with real-time combat and modernized storytelling for new audiences. Explore Midgar in stunning detail, engage in strategic turn-based and real-time combat hybrid system, and witness emotional character moments that expand the original narrative. This faithful yet fresh remake captures the essence of the beloved classic.", director: "Tetsuya Nomura", cast: ["Square Enix"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2020-04-10"), duration: 40, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1462040/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Dark Souls III", description: "Face punishing difficulty in this dark fantasy masterpiece where death teaches and victory feels earned. Explore interconnected worlds brimming with secrets, master challenging combat timing, and defeat epic boss battles that demand skill and perseverance. With atmospheric level design, item discovery, and invasive multiplayer, every moment is tense.", director: "Hidetaka Miyazaki", cast: ["FromSoftware"], genre: ["Action", "Adventure", "Fantasy"], releaseDate: new Date("2016-04-12"), duration: 50, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/374320/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Bloodborne", description: "Hunt cosmic horrors in a Victorian Gothic nightmare where aggressive combat and risk-reward mechanics define survival. Explore Yharnam's twisted streets and nightmarish bosses, master the regain mechanic, and uncover horrifying lore hidden throughout this masterpiece. With unique setting and challenging gameplay, Bloodborne redefined action gaming.", director: "Hidetaka Miyazaki", cast: ["FromSoftware"], genre: ["Action", "Horror", "Thriller"], releaseDate: new Date("2015-03-24"), duration: 45, language: "English", country: "Japan", poster: "https://upload.wikimedia.org/wikipedia/en/6/68/Bloodborne_Cover_Wallpaper.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Monster Hunter: World", description: "Hunt colossal beasts in stunning ecosystems with friends in cooperative multiplayer adventures. Master various weapon types, study monster behaviors, gather materials for armor and weapons, and engage in epic battles that test skill and strategy. With hundreds of hours of content and challenging quests, Monster Hunter World delivers endless hunting excitement.", director: "Yuya Tokuda", cast: ["Capcom"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2018-01-26"), duration: 100, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/582160/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Metal Gear Solid V: The Phantom Pain", description: "Infiltrate enemy bases as Venom Snake using stealth tactics, creative problem-solving, and advanced espionage equipment. Experience a vast open-world military simulator with multiple mission approaches and consequences that affect your playstyle. With cinematic storytelling, deep customization systems, and engaging gameplay, this is an espionage masterpiece.", director: "Hideo Kojima", cast: ["Kojima Productions"], genre: ["Action", "Thriller", "War"], releaseDate: new Date("2015-09-01"), duration: 60, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/287700/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Death Stranding", description: "Reconnect America by delivering cargo across dangerous terrain in this unique action game from Hideo Kojima. Manage weight and balance as you trek through beautiful landscapes, connect people through a communication network, and face mysterious threats. With celebrity cameos, innovative gameplay, and philosophical themes, Death Stranding is unforgettably different.", director: "Hideo Kojima", cast: ["Kojima Productions"], genre: ["Action", "Adventure", "Sci-Fi"], releaseDate: new Date("2019-11-08"), duration: 50, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1850570/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Persona 5", description: "Balance high school life with moonlit adventures as a phantom thief in this stylish JRPG masterpiece. Manage relationships with diverse characters, explore dungeon palaces to reform society, and engage in strategic turn-based combat with stunning animations. With unforgettable music, art direction, and storytelling, Persona 5 is a cultural phenomenon.", director: "Kazari Abe", cast: ["Atlus"], genre: ["Adventure", "Fantasy", "Drama"], releaseDate: new Date("2016-09-15"), duration: 100, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1687950/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Devil May Cry 5", description: "Unleash stylish demon-slaying action with incredible combo systems and character variety. Play as Dante, Nero, and V with unique playstyles, engage in flashy battles against demonic threats, and experience incredible level design. With competitive depth, satisfying combat mechanics, and stunning visuals, DMC5 is an action game masterclass.", director: "Hideaki Itsuno", cast: ["Capcom"], genre: ["Action", "Adventure", "Fantasy"], releaseDate: new Date("2019-03-08"), duration: 20, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/601150/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Resident Evil 4 Remake", description: "Experience survival horror reimagined in a Spanish castle filled with terrifying creatures and intense moments. Play as Leon Kennedy on a rescue mission using tactical combat, resource management, and puzzle-solving to survive. With perfect pacing, memorable encounters, and beautiful graphics, this remake honors the classic while bringing fresh intensity.", director: "Morimasa Sato", cast: ["Capcom"], genre: ["Horror", "Action", "Thriller"], releaseDate: new Date("2023-03-24"), duration: 15, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/2050650/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Street Fighter 6", description: "Fight in stunning 3D environments with deep mechanics appealing to both beginners and competitive players. Master multiple fighting styles, engage in story-driven adventures, and compete online against players worldwide. With innovative mechanics, beautiful visuals, and robust online netcode, SF6 sets a new standard for fighting games.", director: "Takayuki Nakayama", cast: ["Capcom"], genre: ["Action", "Sport", "Drama"], releaseDate: new Date("2023-06-02"), duration: 10, language: "English", country: "Japan", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1364780/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Mortal Kombat 1", description: "Master brutal combat with iconic fighters in this fighting game masterpiece featuring over 40 characters. Execute fatalities, learn combo strings, engage in cinematic story modes, and compete in ranked online tournaments. With visceral combat feedback, balanced gameplay, and stunning visuals, MK1 dominates the fighting game genre.", director: "Ed Boon", cast: ["NetherRealm Studios"], genre: ["Action", "Sport", "Drama"], releaseDate: new Date("2023-09-19"), duration: 12, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1971870/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "NBA 2K24", description: "Experience authentic basketball action with realistic player animations and strategic gameplay mechanics. Build your MyPlayer career, manage a franchise, engage in online multiplayer, and enjoy stunning graphical fidelity. With deep customization and engaging modes, NBA 2K24 is the premier basketball video game.", director: "Visual Concepts", cast: ["2K Sports"], genre: ["Sport", "Drama", "Action"], releaseDate: new Date("2023-09-08"), duration: 1, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/2338770/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "FC 24", description: "Build your ultimate team and compete in the world's most popular football simulation with millions of players worldwide. Engage in squad battles, draft mode, and online multiplayer with realistic player likenesses and authentic league content. With FUT card collecting and strategic team building, FC 24 delivers the ultimate football experience.", director: "EA Sports", cast: ["EA Sports"], genre: ["Sport", "Drama", "Action"], releaseDate: new Date("2023-09-29"), duration: 1, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/2195250/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Gran Turismo 7", description: "Drive prestigious cars on legendary tracks with photorealistic graphics and physics-based simulation. Collect hundreds of vehicles, master racing techniques, compete in events worldwide, and experience the thrill of competitive motorsport. With stunning visuals, realistic mechanics, and endless content, GT7 is a racing masterpiece.", director: "Kazunari Tomi", cast: ["Polyphony Digital"], genre: ["Sport", "Action", "Drama"], releaseDate: new Date("2022-03-04"), duration: 1, language: "English", country: "Japan", poster: "https://www.gran-turismo.com/gtsport/images/metadata_image_en.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Forza Motorsport", description: "Dominate the track in over 500 meticulously detailed cars with advanced customization and tuning options. Experience dynamic weather, time-of-day changes, and track deformation that affects racing conditions. With comprehensive career modes and online competition, Forza delivers the ultimate racing simulator.", director: "Turn 10 Studios", cast: ["Turn 10 Studios"], genre: ["Sport", "Action", "Drama"], releaseDate: new Date("2023-10-10"), duration: 1, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/2440510/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Alan Wake 2", description: "Investigate psychological horror and supernatural mysteries in this mind-bending thriller where reality blurs with nightmare. Play as investigator Saga Anderson and writer Alan Wake, experiencing intertwined narratives across two distinct campaigns. With cerebral storytelling, atmospheric tension, and innovative gameplay, AW2 redefines the horror genre.", director: "Sam Lake", cast: ["Remedy Entertainment"], genre: ["Horror", "Thriller", "Mystery"], releaseDate: new Date("2023-10-27"), duration: 20, language: "English", country: "Finland", poster: "https://upload.wikimedia.org/wikipedia/en/e/ed/Alan_Wake_2_box_art.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Star Wars Jedi: Survivor", description: "Continue Cal Kestis' journey with Force powers and lightsaber combat in this action-adventure masterpiece. Explore iconic Star Wars locations, face powerful enemies, unlock new abilities, and uncover mysteries about the galaxy's past. With cinematic storytelling, satisfying combat, and immersive worlds, this Jedi adventure is unforgettable.", director: "Stig Asmussen", cast: ["Respawn Entertainment"], genre: ["Action", "Adventure", "Sci-Fi"], releaseDate: new Date("2023-04-28"), duration: 30, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1774580/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Minecraft", description: "Create, explore, and survive in infinite blocky worlds limited only by your imagination and creativity. Build magnificent structures, explore dangerous caves, engage in combat, and experience peaceful creative freedom. With endless updates, thriving community, and cross-platform play, Minecraft remains gaming's most played and beloved title.", director: "Markus Persson", cast: ["Mojang Studios"], genre: ["Adventure", "Family", "Drama"], releaseDate: new Date("2011-11-18"), duration: 999, language: "English", country: "Sweden", poster: "https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png", featured: true, isActive: true, addedBy: "system" },
  { title: "Fortnite", description: "Battle 100 players in free-to-play battle royale action with vibrant graphics and constant updates. Build structures, master shooting mechanics, collect loot, and be the last player standing. With crossover events featuring popular franchises, cosmetics, and regular content drops, Fortnite dominates the multiplayer landscape.", director: "Tim Sweeney", cast: ["Epic Games"], genre: ["Action", "Drama", "Adventure"], releaseDate: new Date("2018-07-25"), duration: 1, language: "English", country: "USA", poster: "https://upload.wikimedia.org/wikipedia/en/3/3a/Fortnite.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Call of Duty: Modern Warfare III", description: "Engage in intense multiplayer combat and cooperative campaigns across contemporary battlefields. Master various weapons, execute tactical strategies, complete challenging missions, and compete in fast-paced online matches. With innovative multiplayer maps, powerful weapons, and engaging co-op content, MW3 leads the FPS genre.", director: "Sledgehammer Games", cast: ["Sledgehammer Games"], genre: ["Action", "War", "Thriller"], releaseDate: new Date("2023-11-10"), duration: 1, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/3595270/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Grand Theft Auto V", description: "Explore a massive open world filled with crime, entertainment, and endless possibilities in this gaming masterpiece. Control three protagonists with distinct personalities, engage in thrilling heists, participate in various activities, and experience a living, breathing world. With stunning graphics, engaging narrative, and infinite emergent gameplay, GTA V sets the bar for open-world games.", director: "Dan Houser", cast: ["Rockstar Games"], genre: ["Action", "Adventure", "Crime"], releaseDate: new Date("2013-09-17"), duration: 120, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "League of Legends", description: "Battle against players worldwide in this legendary MOBA with 160+ unique champions and deep strategic gameplay. Master champion abilities, coordinate with teammates, secure objectives, and claim victory through teamwork and skill. With competitive ranked play, regular balance updates, and an esports scene, LoL remains gaming's most played PC game.", director: "Marc Merrill", cast: ["Riot Games"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2009-10-27"), duration: 1, language: "English", country: "USA", poster: "https://upload.wikimedia.org/wikipedia/commons/d/d8/League_of_Legends_2019_vector.svg", featured: true, isActive: true, addedBy: "system" },
  { title: "Dota 2", description: "Compete in intense team-based battles with 120+ heroes and infinitely complex strategic gameplay. Master hero abilities, item builds, and map control in 5v5 matches against opponents worldwide. With an engaged esports community, international tournaments offering millions in prizes, and constant updates, Dota 2 is a competitive phenomenon.", director: "IceFrog", cast: ["Valve Corporation"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2013-07-09"), duration: 1, language: "English", country: "USA", poster: "https://www.dota2.com/images/social-share-image.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Counter-Strike 2", description: "Experience the evolution of competitive FPS gaming with refined mechanics, improved graphics, and enhanced netcode. Execute coordinated strategies, master weapon economics, engage in intense 5v5 matches, and compete in world-class tournaments. With accessibility for beginners and depth for professionals, CS2 dominates competitive FPS.", director: "Valve Corporation", cast: ["Valve Corporation"], genre: ["Action", "War", "Drama"], releaseDate: new Date("2023-09-01"), duration: 1, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Valorant", description: "Master tactical shooter gameplay with unique agents possessing distinct abilities that define team composition. Execute precise aim, coordinate ultimate abilities, manage economy rounds, and engage in strategic 5v5 matches. With perfect netcode, diverse agents, and thriving esports ecosystem, Valorant revolutionized the tactical shooter genre.", director: "Riot Games", cast: ["Riot Games"], genre: ["Action", "War", "Drama"], releaseDate: new Date("2020-06-02"), duration: 1, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/2128652/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Overwatch 2", description: "Team-based hero shooter action with diverse heroes offering multiple playstyles and team compositions. Master hero abilities, coordinate ultimate combos, secure objectives, and compete in intense 5v5 matches. With constant hero updates, seasonal events, and balanced gameplay, OW2 defines cooperative FPS excellence.", director: "Blizzard Entertainment", cast: ["Blizzard Entertainment"], genre: ["Action", "War", "Drama"], releaseDate: new Date("2022-10-04"), duration: 1, language: "English", country: "USA", poster: "https://overwatch.blizzard.com/en-us/media/overwatch-2-heroes-4x3.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Apex Legends", description: "Drop into battle royale action with unique legends possessing special abilities that reshape gameplay strategy. Execute fast-paced combat, master positioning, secure loot, and eliminate squads in 3v3 matches. With diverse legends, engaging seasons, and skill-based gameplay, Apex Legends leads the battle royale genre.", director: "Respawn Entertainment", cast: ["Respawn Entertainment"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2019-02-04"), duration: 1, language: "English", country: "USA", poster: "https://www.ea.com/sites/default/files/content/dam/eacom/en-us/images/2019/02/apex-legends-og-image.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Warframe", description: "Experience fast-paced co-op action as powerful Tenno warriors wielding diverse frame abilities and weapons. Execute aerial acrobatics, unlock frames with unique powers, engage in cooperative missions, and explore vast environments. With endless progression, regular updates, and cooperative focus, Warframe remains gaming's premier co-op shooter.", director: "Digital Extremes", cast: ["Digital Extremes"], genre: ["Action", "Adventure", "Sci-Fi"], releaseDate: new Date("2013-03-25"), duration: 1, language: "English", country: "Canada", poster: "https://cdn.akamai.steamstatic.com/steam/apps/230410/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Path of Exile", description: "Dive into dark fantasy action-RPG combat with endless build possibilities and depth of itemization. Master skill gems, craft powerful equipment, engage in challenging endgame content, and experience a game constantly evolving with new mechanics. With free-to-play accessibility and respectful monetization, PoE is an action-RPG phenomenon.", director: "Grinding Gear Games", cast: ["Grinding Gear Games"], genre: ["Action", "Adventure", "Fantasy"], releaseDate: new Date("2013-10-23"), duration: 1, language: "English", country: "New Zealand", poster: "https://www.pathofexile.com/image/og-image.png", featured: true, isActive: true, addedBy: "system" },
  { title: "Lost Ark", description: "Explore a vast isometric world in this action MMORPG with dynamic combat and cooperative dungeon experiences. Master various classes, engage in PvP and PvE content, complete engaging story quests, and participate in world events. With beautiful visuals, diverse content, and thriving player community, Lost Ark offers immersive MMO experience.", director: "Smilegate", cast: ["Smilegate"], genre: ["Action", "Adventure", "Sci-Fi"], releaseDate: new Date("2022-02-11"), duration: 1, language: "English", country: "South Korea", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1599340/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "New World", description: "Enter a mysterious 17th century fantasy world as an MMO adventurer exploring, fighting, and crafting. Engage in large-scale PvP wars between factions, tackle challenging dungeons, master various weapons and abilities. With dynamic leveling systems and emphasis on player-driven economy, New World reimagines MMO gameplay.", director: "Amazon Game Studios", cast: ["Amazon Game Studios"], genre: ["Adventure", "Fantasy", "Drama"], releaseDate: new Date("2021-09-28"), duration: 1, language: "English", country: "USA", poster: "https://cdn.akamai.steamstatic.com/steam/apps/1063730/header.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Final Fantasy XIV", description: "Join millions in this beloved MMORPG with epic storylines, engaging characters, and rewarding endgame content. Engage in challenging raids, master various job classes, participate in seasonal events, and experience one of gaming's finest narratives. With welcoming community and constant quality updates, FFXIV is an MMO masterpiece.", director: "Yoshi-P", cast: ["Square Enix"], genre: ["Adventure", "Fantasy", "Drama"], releaseDate: new Date("2010-09-30"), duration: 1, language: "English", country: "Japan", poster: "https://www.finalfantasyxiv.com/images/site/og-image.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "World of Warcraft", description: "The legendary MMORPG that shaped the genre continues to deliver quality content and immersive world exploration. Master 13 character classes, engage in challenging raids and dungeons, participate in dynamic PvP, and experience rich Warcraft lore. With decades of content and dedicated player base, WoW remains a gaming institution.", director: "Blizzard Entertainment", cast: ["Blizzard Entertainment"], genre: ["Adventure", "Fantasy", "Drama"], releaseDate: new Date("2004-11-23"), duration: 1, language: "English", country: "USA", poster: "https://www.worldofwarcraft.com/en-us/media/world-of-warcraft-social-share.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Halo Infinite", description: "Join Master Chief on an epic sci-fi adventure across a mysterious Halo ring with stunning multiplayer experiences. Experience campaign missions with explosive action, engage in fast-paced online multiplayer, and customize your Spartan. With free-to-play multiplayer and rich narrative campaign, Halo Infinite reignites the franchise's glory.", director: "343 Industries", cast: ["343 Industries"], genre: ["Action", "Sci-Fi", "Adventure"], releaseDate: new Date("2021-12-08"), duration: 12, language: "English", country: "USA", poster: "https://www.haloinfinite.com/en-us/media/og-image.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Assassin's Creed: Mirage", description: "Experience parkour and stealth action in historic Baghdad during the Golden Age of Islam in this Assassin's Creed adventure. Master parkour movements, engage in fluid combat, complete assassination contracts, and uncover mysteries of the Assassin Brotherhood. With stunning visuals and refined mechanics, Mirage returns to the franchise's roots.", director: "Stephanie Boucher", cast: ["Ubisoft"], genre: ["Action", "Adventure", "History"], releaseDate: new Date("2023-10-05"), duration: 40, language: "English", country: "Canada", poster: "https://www.ubisoft.com/en-us/game/assassins-creed-mirage/media/og-image.jpg", featured: true, isActive: true, addedBy: "system" },
  { title: "Spider-Man 2", description: "Swing through NYC as Spider-Man in this superhero action game featuring Peter Parker and Miles Morales. Master web-slinging mechanics, engage in spectacular combat against super-villains, complete challenging missions. With dynamic city interaction, engaging narrative, and satisfying gameplay, Spider-Man 2 is the definitive web-slinger experience.", director: "Bryan Intihar", cast: ["Insomniac Games"], genre: ["Action", "Adventure", "Drama"], releaseDate: new Date("2023-10-20"), duration: 30, language: "English", country: "USA", poster: "https://image.api.playstation.com/vulcan/ap/rnd/202306/0920/0f0e2e4a1c6b7a8d9f0a1b2c3d4e5f6a7b8c9d0e.jpg", featured: true, isActive: true, addedBy: "system" },
];

async function seedMovies() {
  try {
    await connectDB();

    // Clear existing movies
    await Movie.deleteMany({});
    console.log("Cleared existing movies");

    // Insert sample movies
    const insertedMovies = await Movie.insertMany(sampleMovies);
    console.log(`Inserted ${insertedMovies.length} movies:`);
    insertedMovies.forEach((movie) => {
      console.log(`- ${movie.title} (ID: ${movie._id})`);
    });

    console.log("Database seeded successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    await mongoose.disconnect();
  }
}

seedMovies();
