import "dotenv/config";
import mongoose from "mongoose";
import Game from "../models/Game.js";
import connectDB from "../config/database.js";

const detailedDescriptions = {
  "Grand Theft Auto VI":
    "The most anticipated game of the decade finally arrives. Return to Vice City and the surrounding state of Leonida in this massive open-world crime epic that pushes gaming technology to new heights. Play as Lucia and Jason in a modern-day Bonnie and Clyde narrative across a sprawling, hyper-detailed world. Every neighborhood has its own culture and rhythm. Dynamic world events, reactive AI, and an evolving ecosystem make Leonida feel alive. Improved combat mechanics include refined gunplay, deep hand-to-hand systems, and expanded vehicle combat. The online component launches with a全新的 shared-world experience featuring heists, businesses, and community events. Rockstar's signature storytelling, cutting-edge graphics, and infinite emergent gameplay redefine what video games can achieve. With ray-tracing, physics-driven destruction, and a soundtrack spanning decades of hits, GTA VI sets a new benchmark for interactive entertainment.",

  "Monster Hunter Wilds":
    "Hunt colossal monsters in a breathtaking open world where ecosystems evolve in real-time with dynamic weather, changing seasons, and living wildlife. Master 14 distinct weapon types, from the nimble dual blades to the devastating great sword, each with unique move sets and mechanics. Track monsters through dynamic environments where storms alter terrain, seasonal changes affect monster behavior, and resource availability shifts with the ecosystem. Seamless co-op hunting allows up to four players to team up across platforms with full cross-play support. The new mount system lets you ride and fight from your Seikret, adding vertical mobility and tactical options. The roster of monsters is the most ambitious in series history, including returning fan favorites and brand-new apex predators. Environments react to your actions, creating emergent gameplay moments that make every hunt unique. A living world that evolves with every expedition.",

  "Doom: The Dark Ages":
    "Rip and tear through a medieval fantasy world where demons have conquered the kingdom. As the legendary Slayer, wield brutal dark-age weaponry from enchanted swords and devastating maces to demon-infused crossbows and siege-grade ballistas. Explore sprawling gothic castles, hell-infested dungeons, corrupted forests, and besieged towns. Each environment tells a story of the demonic invasion through environmental storytelling and hidden lore. Combat is fluid and visceral, demanding constant movement, weapon switching, and strategic use of the environment. The new shield-saw lets you parry attacks, deflect projectiles, and rip enemies apart. Devastating finishers unleash screen-shaking glory kills that vary based on enemy type and environment. id Software's signature fluid combat engine delivers relentless action with a haunting heavy metal soundtrack that intensifies with the carnage. An epic prequel to the modern Doom saga.",

  "Death Stranding 2: On the Beach":
    "Continue Sam Bridges' extraordinary journey in a world struggling to reconnect after extinction-level events. Traverse hauntingly beautiful landscapes spanning vast tundras, sun-scorched deserts, and crumbling urban ruins. Face new supernatural threats called the 'Beach', a liminal space between life and death that bleeds into reality. Expanded traversal mechanics include improved vehicles, grappling hooks, zip-lines, and new equipment that fundamentally changes how you navigate. Combat has been completely redesigned with deeper stealth options, direct confrontation tools, and the ability to command NPC allies. The social strand system returns with more meaningful player connections and community-built infrastructure. Hideo Kojima's signature storytelling weaves emotional performances, philosophical themes, and thought-provoking narrative twists into an unforgettable experience. Featuring Norman Reedus, Léa Seydoux, and new cast members in a story that challenges perceptions of life, death, and human connection.",

  "Assassin's Creed Shadows":
    "Feudal Japan comes alive in breathtaking detail in this landmark Assassin's Creed adventure. Play as Naoe, a shinobi assassin who uses stealth, agility, and environmental tricks to eliminate targets, and Yasuke, the legendary African samurai who commands devastating melee combat and can face armies head-on. The dual-protagonist system lets you switch between characters, each with unique abilities, progression trees, and mission approaches. Explore a stunningly rendered 16th-century Japan spanning 30+ detailed cities, castles, and wilderness regions. Dynamic seasons transform the world: spring cherry blossoms obscure vision, summer rains silence footsteps, autumn leaves provide cover, and winter snow preserves footprints for tracking. Each season unlocks unique gameplay opportunities and challenges. The legendary Assassin vs. Templar conflict unfolds against a meticulously researched historical backdrop. Player choices reshape territories, alliances, and the fates of historical figures.",

  Avowed:
    "Explore the living world of Eora in this ambitious first-person RPG from Obsidian Entertainment, creators of Pillars of Eternity and The Outer Worlds. As an envoy of the Aedyr Empire, investigate a mysterious plague known as the Dreamscourge spreading through the Living Lands. Wield swords, axes, wands, and firearms in fluid real-time combat with seamless weapon switching and magical spellcasting. The deep ability system lets you mix and match skills from three skill trees: warrior, ranger, and wizard. Every choice matters — dialogue decisions, faction alliances, and quest outcomes reshape the world and determine the fate of its inhabitants. The reactive world changes based on your actions: towns remember your deeds, NPCs respond to your reputation, and major plot points branch based on your decisions. Obsidian's hallmark reactive storytelling delivers meaningful consequences and multiple endings. A richly detailed fantasy world with deep lore, compelling characters, and immersive exploration.",

  "Metroid Prime 4: Beyond":
    "Samus Aran returns in a brand-new first-person adventure that pushes the boundaries of the Metroid Prime formula to new heights. Explore alien worlds with unprecedented visual fidelity, from lush alien jungles to derelict space stations corrupted by Phazon. Engage in precision combat using Samus's full arsenal: arm cannon with multiple beam types, missiles, morph ball bombs, and new abilities. The iconic visor system returns with expanded scanning modes: combat visor for targeting, scan visor for lore and puzzles, thermal visor for hidden enemies, and new visor types that reveal dimensional anomalies. Environmental puzzles require creative use of upgrades and sequence-breaking opportunities for veteran players. Improved movement mechanics include wall jumps, speed booster, and new grapple techniques that make traversal fluid and rewarding. Intense boss battles test your mastery of combat and movement. A masterful blend of exploration, combat, and atmospheric storytelling that defines the Metroid franchise.",

  "Ghost of Yotei":
    "Set 300 years after the events of Ghost of Tsushima, a new Ghost rises in the shadow of Mount Yotei in feudal Japan's northern frontier. Play as Atsu, a warrior haunted by her past, armed with a new arsenal of weapons including dual katanas, chain sickles, and explosive powder bombs. The vast Ezo region features snow-capped mountains, dense forests, sprawling plains, and coastal villages, each with distinct weather and seasonal cycles that dynamically affect gameplay. Deep snow muffles footsteps but leaves tracks, rain extinguishes your bow, and fog limits visibility. New Ghost weapons expand tactical options: smoke bombs for escapes, wind chimes for distractions, and sticky bombs for traps. The stand-off system returns with new multi-enemy chain assassinations. A gripping story of vengeance, redemption, and identity unfolds against stunning landscapes rendered with Sucker Punch's signature visual artistry. Wind guides you to objectives, fireflies mark points of interest, and wildlife reacts to your presence.",

  "Borderlands 4":
    "The signature looter-shooter returns bigger, bolder, and more chaotic than ever with billions of procedurally generated weapons, each with unique handling, elemental effects, and special abilities. Explore a never-before-seen planet on the edge of known space, featuring diverse biomes from toxic wastelands and crystal forests to floating archipelagoes and alien hive cities. Choose from an all-new Vault Hunter roster, each with devastating action skills and deep skill trees that enable radically different playstyles. Drop-in/drop-out four-player co-op with dynamic difficulty scaling ensures the mayhem scales with your party. New elemental damage systems create devastating synergies, vehicle combat enhancements include customizable vehicles with mounted weapons, and the most chaotic skill trees yet offer unprecedented build variety. The signature cel-shaded art style returns with enhanced lighting and physics. Mayhem modifiers return with new game-altering mutations. Billions of guns. Infinite mayhem. Your next Vault Hunt begins now.",

  "Sid Meier's Civilization VII":
    "Lead your civilization from ancient antiquity to the distant space age in the next evolution of the legendary 4X strategy franchise. New gameplay systems fundamentally change how empires are built and managed. Dynamic diplomacy features AI leaders with genuine personalities who remember past grievances and alliances, negotiating with trade deals, territorial disputes, and military alliances. Enhanced warfare tactics include combined arms bonuses, siege mechanics, and commander units that provide army-wide buffs. Deeper cultural development paths let you shape your civilization's identity through government policies, religious beliefs, and philosophical traditions. The new age system divides history into distinct eras, each with unique challenges and victory conditions. Choose from the most diverse roster of leaders in franchise history, each with unique abilities, agendas, and customizable traits. Build your empire through science, culture, military might, economic dominance, or religious influence. The most ambitious Civilization game yet. One more turn...",


  "Split Fiction":
    "From Hazelight Studios, the award-winning creators of It Takes Two, comes a boundary-pushing co-op adventure where two writers, Zoe and Mio, become trapped inside their own stories. Navigate a genre-defying world that seamlessly shifts between sci-fi and fantasy, from cyberpunk cities and space stations to enchanted forests and dragon-guarded castles. Each level introduces unique mechanics that require constant communication and coordination between players. One player might manipulate gravity while the other controls time. Solve creative puzzles that demand both players contribute their unique abilities. Overcome dynamic obstacles that change in real-time based on your actions. Experience a heartfelt story about creativity, friendship, and the power of collaboration. Unique dual-character mechanics mean no two playthroughs are identical. Friend Pass lets one player invite another for free. This is cooperative gaming at its absolute finest.",

  Fable:
    "The legendary RPG series returns with a brand-new adventure filled with British humor, morally complex choices, and magical mayhem. Explore the land of Albion like never before — a sprawling fantasy world where every action has consequences. Your choices shape your character physically: good deeds make you radiant and attract helpful NPCs, while evil deeds cause physical corruption and inspire fear. Magic and melee combat have been completely reimagined with fluid real-time combat that lets you chain sword strikes, spells, and special abilities. Build relationships with villagers, get married, buy property, and build a family. The world ages around you: children become adults, buildings crumble or get renovated based on the economy, and your legend grows with every deed. Playground Games brings the beloved series into a stunning new era with cutting-edge visuals, a massive open world, and the signature humor that defined the franchise. Your story. Your choices. Your legend.",

  "The First Berserker: Khazan":
    "A hardcore action RPG set in the Dungeon Fighter Online universe that delivers punishing yet rewarding combat. As Khazan, the legendary berserker framed for treason, fight through brutal battlefields using precision-based combat mechanics that demand mastery of timing and positioning. Master three distinct weapon styles: dual swords for speed and combos, greatsword for power and reach, and spear for precision and crowd control. The parry system is central to combat — perfectly timed blocks leave enemies staggered and open for devastating counter-attacks. Unleash special skills through the skill tree, customizing Khazan's abilities to match your preferred playstyle. Challenging boss encounters are the highlight, each with unique attack patterns, phases, and weaknesses to discover. Stunning cel-shaded visuals bring the world to life with a distinctive art style that blends traditional Korean aesthetics with dark fantasy. A gripping revenge story set in a beautifully brutal world.",

  Atomfall:
    "Survive in a uniquely British post-apocalyptic open world set five years after the catastrophic Windscale nuclear disaster of 1957. The English countryside has been transformed into a radioactive wilderness, with towering nuclear vents, mutated wildlife, and desperate survivor settlements. Scavenge resources from abandoned villages, military outposts, and secret underground bunkers. Craft weapons, tools, and medicine from salvaged materials using an extensive crafting system. Investigate mysterious radio signals that lead to hidden facilities, secret government experiments, and a conspiracy that reaches the highest levels of power. Navigate irradiated zones with a Geiger counter, managing radiation exposure while searching for valuable loot. Face mutated creatures and desperate survivors who may be friend or foe. With its distinctive British setting, immersive survival mechanics, branching narrative, and multiple endings, Atomfall offers a uniquely British take on post-apocalyptic survival.",

  "Elden Ring Nightreign":
    "A standalone co-op survival experience set in the Elden Ring universe that combines signature FromSoftware challenge with roguelike mechanics. Face the Nightlord across three procedurally generated in-game days and nights, each cycle bringing new threats, rewards, and environmental conditions. By day, explore a shifting map to discover dungeons, defeat minibosses, and gather powerful equipment and upgrades. As night falls, the world becomes more dangerous with enhanced enemies and environmental hazards. Choose from unique classes with specialized abilities, combat styles, and ultimate skills. Master new mechanics including mounted combat, aerial attacks, and environmental interactions. The rune system lets you permanently unlock account-wide bonuses between runs. Faithful to the signature challenge while introducing fresh roguelike elements, this is a new way to experience the Lands Between. The night is dark and full of terrors. Survive.",

  "Mafia: The Old Country":
    "Experience the brutal origins of organized crime in 1900s Sicily in this gritty open-world crime drama from Hangar 13. Step into the boots of Enzo, a young man drawn into the world of the Sicilian Mafia during the tumultuous early 20th century. Build your criminal empire from the ground up through extortion, smuggling, and strategic alliances. Earn respect through brutal enforcement and navigate the complex codes of honor, loyalty, and silence that governed the original Cosa Nostra. Explore a beautifully realized historical Sicily: from the dusty streets of small villages to the opulent villas of wealthy landowners, from hidden mountain passes to bustling port cities. The authentic period detail extends to weapons, vehicles, and fashion of the era. Cinematic mission design with branching paths and moral choices that affect your standing with the family. A compelling prequel rooted in tradition, betrayal, and the making of an American legend.",

  "Like a Dragon: Pirate Yakuza in Hawaii":
    "Set sail for the most outrageous adventure in the Yakuza series yet as Goro Majima, now an amnesiac pirate captain washing ashore on a tropical island. Explore the seas around Hawaii in naval combat, commanding your own pirate ship with customizable weapons and crew. Switch between two combat styles: Mad Dog, a return to Majima's signature breakdance-inspired brutality, and Sea Dog, a new swashbuckling style featuring cutlass slashes and pistol shots. Build your pirate crew by recruiting colorful characters from across the series, each with unique abilities and side stories. Manage your ship, upgrade its weapons and speed, and engage in naval battles with rival pirate fleets. Explore sunken ruins, hidden coves, and treasure islands. The signature RGG Studio blend of serious drama and absurd humor is in full effect, with emotional main story beats and ridiculous side content including karaoke, arcade games, and the return of Cabaret Club. Yo-ho-ho, it's Yakuza like you've never seen it.",

  "Clair Obscur: Expedition 33":
    "A stunning turn-based RPG set in a painterly world where a mysterious Paintress annually erases a color from existence, killing everyone associated with it. Lead Expedition 33 on a desperate mission to confront the Paintress and end her devastating cycle. Explore a universe where beauty and danger intertwine, from the vibrant Belle Époque-inspired streets of Lumière to the monochrome wastelands of the Erased. The combat system blends traditional turn-based strategy with real-time action elements: time your attacks for critical hits, dodge incoming attacks with precise button presses, and chain abilities for devastating combos. The painterly art style evolves as colors are erased, with the world literally losing hues as the Paintress works. An emotional narrative explores themes of loss, memory, and sacrifice. Unique companion characters each have distinct combat roles and personal stories. One of the most visually striking RPGs ever made, with a soundtrack that adapts to your journey.",

  "South of Midnight":
    "Immerse yourself in the haunted American Deep South in this third-person action-adventure from Compulsion Games. Play as Hazel, a weaver with the supernatural ability to see and mend broken spirits, unravel curses, and restore balance to a world teetering between the living and the dead. Explore a beautifully grotesque world inspired by Southern Gothic folklore and mythology, from moss-draped bayous and crumbling antebellum mansions to hidden creature-filled caves and ghost-haunted swamps. Battle twisted creatures born from human misery using Hazel's weaving powers: mend enemies to weaken them, unravel their curses, and banish them with powerful spells. The unique art style blends stop-motion animation aesthetics with modern graphics technology, creating a distinctive visual identity. Uncover family secrets spanning generations, make moral choices that affect the spirit world, and discover the true cost of the supernatural. A deep, emotional journey through myth, memory, and the American South.",

  "The Witcher IV":
    "The next epic chapter in the Witcher saga begins, with Ciri taking her place as the protagonist. Hunt monsters across a vast continent transformed by war, political upheaval, and a mysterious cataclysm that has unleashed never-before-seen creatures. Master new magical abilities that build on Ciri's unique connection to Elder Blood, allowing unprecedented combat and exploration capabilities. Craft powerful witcher gear using new alchemy and crafting systems that offer deeper customization. Make morally complex choices that reshape the world — entire regions can change based on your decisions, factions rise and fall, and characters live or die by your actions. CD Projekt Red's next-generation REDengine delivers breathtaking visuals with ray-tracing, photorealistic characters, and a living world that reacts to your presence. Deeply reactive storytelling with multiple branching paths and endings ensures no two playthroughs are identical. A legend is reborn. The Witcher saga continues.",

  "Marvel's Wolverine":
    "Unleash your animal instincts in this visceral third-person action game from Insomniac Games, the studio behind Marvel's Spider-Man. Play as Logan — the best there is at what he does — in a mature, emotionally charged narrative that explores the character's brutal past and tortured present. Combat is raw and savage: tear through enemies with adamantium claws in fluid, cinematic combat that combines fast-paced melee attacks, stealth takedowns, and environmental kills. The rage system builds as you take damage, unlocking devastating berserker abilities that turn the tide of battle. Your regenerative healing factor is integrated into gameplay as a resource that recovers health but can be overwhelmed by sustained damage. Explore locations from seedy dive bars and Weapon X facilities to wilderness cabins and international espionage hubs. With the same care, polish, and quality that defined Marvel's Spider-Man, Insomniac brings the X-Men's most iconic mutant to life in a story-driven action game. The best there is. The best there ever will be.",

  "Gears of War: E-Day":
    "Return to the horrors of Emergence Day in this intense, harrowing prequel to the Gears of War saga. Witness the Locust Horde's first assault on humanity through the eyes of young Marcus Fenix and Dom Santiago, before they became battle-hardened veterans. Experience the terror of first contact as the Locust emerge from below, destroying cities and throwing humanity into chaos. Fight desperate last-stand battles through the streets of cities as civilization crumbles around you. The Coalition delivers visceral, cover-based combat at its finest with Unreal Engine 5's stunning visual fidelity — every bullet impact, every shattered wall, every brutal execution is rendered in breathtaking detail. The weight and impact of the Gnasher shotgun and Lancer assault rifle have never felt more devastating. A deeply emotional story explores the bonds of brotherhood forged in the crucible of war. Witness the birth of the COG and the desperate measures humanity took to survive. Welcome to E-Day.",

  "Mass Effect 5":
    "The next chapter in BioWare's beloved sci-fi saga continues, set in a galaxy still recovering from the Reaper War. A new hero rises to unite the fractured species of the galaxy against an emerging threat that could end all life. Discover never-before-seen worlds, from thriving alien civilizations to ancient ruins holding secrets of the Reapers' true origins. Build your crew from a diverse cast of characters, each with deep personal stories, loyalty missions, and romantic possibilities. Refined combat blends the tactical squad-based shooting of Mass Effect 3 with new mobility options including jetpacks, sliding, and enhanced biotics. Make choices that ripple across the galaxy and return in unexpected ways across the story. Beloved species and locations return alongside new alien races and unexplored systems. Deep character relationships are at the heart of the experience — your crew is your family, and their fates rest in your hands. The galaxy needs a new legend. That legend is you.",
};

async function main() {
  await connectDB();

  // Update descriptions
  for (const [title, description] of Object.entries(detailedDescriptions)) {
    const game = await Game.findOne({ title });
    if (!game) { console.log(`NOT FOUND: ${title}`); continue; }
    const existing = game.screenshots || [];
    let screenshots = [...existing];

    // Ensure at least 2 images by duplicating poster if needed
    if (screenshots.length === 0 && game.poster) {
      screenshots = [game.poster];
    }
    if (screenshots.length === 1 && game.poster && !screenshots.includes(game.poster)) {
      screenshots.unshift(game.poster);
    }

    await Game.findByIdAndUpdate(game._id, {
      $set: { description, screenshots },
    });
    console.log(`✅ ${title}: desc=${description.length} chars, screenshots=${screenshots.length}`);
  }

  process.exit(0);
}

main();
